In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.models import Sequential
import keras
keras.utils.set_random_seed(28)
import datetime
from icecream import ic
from itertools import product
from sklearn.preprocessing import MinMaxScaler
import wandb
from configparser import ConfigParser
from sklearn.model_selection import train_test_split

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1776448071.371440  305242 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1776448071.372176  305242 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1776448071.423832  305242 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1776448072.985195  305242 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1776448072.985671  305242 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

In [ ]:
config = ConfigParser()
config.read("credentials.ini")
wandb_api_key = config["WandB"]["api_key"]

In [3]:
CUSTOM_DATASET_PATH = Path("custom_data/")

In [4]:
merged = pd.read_csv(CUSTOM_DATASET_PATH / "merged.csv")
merged

,business_id,latitude,longitude,stars_business,review_count_review,Fuzhou_category,Themed Cafes_category,Burmese_category,Falafel_category,Cafes_category,...,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos,number_of_friends
0,MTSW4McQd7CbVtyjqoe9mw,39.955505,-75.155564,4.0,80,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
1,MTSW4McQd7CbVtyjqoe9mw,39.955505,-75.155564,4.0,80,0,0,0,0,0,...,6,1,0,11,28,46,46,26,20,186
2,MTSW4McQd7CbVtyjqoe9mw,39.955505,-75.155564,4.0,80,0,0,0,0,0,...,0,0,0,3,8,2,2,5,0,18
3,MTSW4McQd7CbVtyjqoe9mw,39.955505,-75.155564,4.0,80,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
4,MTSW4McQd7CbVtyjqoe9mw,39.955505,-75.155564,4.0,80,0,0,0,0,0,...,0,1,4,24,51,35,35,13,5,141
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511133,WnT9NIzQgLlILjPT0kEcsQ,39.935982,-75.158665,4.5,35,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
511134,WnT9NIzQgLlILjPT0kEcsQ,39.935982,-75.158665,4.5,35,0,0,0,0,0,...,0,0,0,3,3,4,4,1,3,6
511135,WnT9NIzQgLlILjPT0kEcsQ,39.935982,-75.158665,4.5,35,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
511136,WnT9NIzQgLlILjPT0kEcsQ,39.935982,-75.158665,4.5,35,0,0,0,0,0,...,0,0,0,5,0,0,0,0,0,77
511137,WnT9NIzQgLlILjPT0kEcsQ,39.935982,-75.158665,4.5,35,0,0,0,0,0,...,0,0,0,6,2,4,4,2,0,79

In [5]:
weekdays = ("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")
merged = merged.drop(columns=[weekday.lower() + suffix for weekday, suffix in product(weekdays, ("_opening", "_closing", "_opening_length_hours"))])

In [6]:
merged = merged.drop(columns=["latitude", "longitude"])

In [7]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    display(merged.isnull().sum())

business_id                                         0
stars_business                                      0
review_count_review                                 0
Fuzhou_category                                     0
Themed Cafes_category                               0
Burmese_category                                    0
Falafel_category                                    0
Cafes_category                                      0
Conveyor Belt Sushi_category                        0
Australian_category                                 0
Sushi Bars_category                                 0
Mongolian_category                                  0
New Mexican Cuisine_category                        0
Poutineries_category                                0
Ethiopian_category                                  0
Hong Kong Style Cafe_category                       0
Cafeteria_category                                  0
Chicken Shop_category                               0
Vegetarian_category                                 0
Asian Fusion_category                               0
Pan Asian_category                                  0
Dinner Theater_category                             0
Hawaiian_category                                   0
Fish & Chips_category                               0
French_category                                     0
Filipino_category                                   0
Seafood_category                                    0
Szechuan_category                                   0
Modern European_category                            0
Himalayan/Nepalese_category                         0
Senegalese_category                                 0
Portuguese_category                                 0
Delis_category                                      0
Vegan_category                                      0
Spanish_category                                    0
Uzbek_category                                      0
Iberian_category                                    0
Steakhouses_category                                0
Italian_category                                    0
Trinidadian_category                                0
Lebanese_category                                   0
Wraps_category                                      0
Bangladeshi_category                                0
Diners_category                                     0
Tapas Bars_category                                 0
Israeli_category                                    0
Pizza_category                                      0
Hainan_category                                     0
Korean_category                                     0
Tapas/Small Plates_category                         0
Russian_category                                    0
Afghan_category                                     0
Mexican_category                                    0
Live/Raw Food_category                              0
Greek_category                                      0
Teppanyaki_category                                 0
Polish_category                                     0
Hot Pot_category                                    0
Hot Dogs_category                                   0
Hungarian_category                                  0
Indian_category                                     0
Food Stands_category                                0
German_category                                     0
Southern_category                                   0
Indonesian_category                                 0
African_category                                    0
Sardinian_category                                  0
Buffets_category                                    0
Cambodian_category                                  0
Waffles_category                                    0
Sandwiches_category                                 0
Chinese_category                                    0
Dominican_category                                  0
Barbeque_category                                   0
Salad_category                                      0
Ukrainian_category                                  0
Vietnamese_category                                 0
Soul Food_category                                  0
Supper Clubs_category                               0
Gluten-Free_category                                0
Soup_category                                       0
Gastropubs_category                                 0
Tex-Mex_category                                    0
Kebab_category                                      0
Tacos_category                                      0
Scandinavian_category                               0
Food Court_category                                 0
Irish_category                                      0
Cajun/Creole_category                               0
Armenian_category                                   0
Laotian_category                                    0
Comfort Food_category                               0
Cantonese_category                                  0
Brasseries_category                                 0
Kosher_category                                     0
Haitian_category                                    0
Dim Sum_category                                    0
Cuban_category                                      0
Chicken Wings_category                              0
Colombian_category                                  0
Peruvian_category                                   0
Basque_category                                     0
Mediterranean_category                              0
Honduran_category                                   0
Ramen_category                                      0
Pop-Up Restaurants_category                         0
Fast Food_category                                  0
Latin American_category                             0
Persian/Iranian_category                            0
Puerto Rican_category                               0
Brazilian_category                                  0
Argentine_category                                  0
Creperies_category                                  0
Sicilian_category                                   0
Pakistani_category                                  0
Georgian_category                                   0
Belgian_category                                    0
Noodles_category                                    0
Caribbean_category                                  0
Singaporean_category                                0
Breakfast & Brunch_category                         0
Burgers_category                                    0
South African_category                              0
Venezuelan_category                                 0
Halal_category                                      0
Turkish_category                                    0
Thai_category                                       0
British_category                                    0
Japanese_category                                   0
Shanghainese_category                               0
Middle Eastern_category                             0
Salvadoran_category                                 0
Izakaya_category                                    0
American (New)_category                             0
Malaysian_category                                  0
Moroccan_category                                   0
Taiwanese_category                                  0
Japanese Curry_category                             0
American (Traditional)_category                     0
Cheesesteaks_category                               0
AmbienceRomantic_attribute_False                    0
AmbienceRomantic_attribute_True                     0
AmbienceRomantic_attribute_no_info                  0
AmbienceHipster_attribute_False                     0
AmbienceHipster_attribute_True                      0
AmbienceHipster_attribute_no_info                   0
NoiseLevel_attribute_average                        0
NoiseLevel_attribute_loud                           0
NoiseLevel_attribute_no_info                        0
NoiseLevel_attribute_quiet                          0
NoiseLevel_attribute_very_loud                      0
RestaurantsCounterService_attribute_True            0
RestaurantsCounterService_attribute_no_info         0
DietaryRestrictionsDairy-free_attribute_False       0
DietaryRestrictionsDairy-free_attribute_no_info     0
AmbienceIntimate_attribute_False                    0
AmbienceIntimate_attribute_True                     0
AmbienceIntimate_attribute_no_info                  0
GoodForMealBrunch_attribute_False                   0
GoodForMealBrunch_attribute_True                    0
GoodForMealBrunch_attribute_no_info                 0
BusinessParkingGarage_attribute_False               0
BusinessParkingGarage_attribute_True                0
BusinessParkingGarage_attribute_no_info             0
RestaurantsPriceRange2_attribute_1                  0
RestaurantsPriceRange2_attribute_2                  0
RestaurantsPriceRange2_attribute_3                  0
RestaurantsPriceRange2_attribute_4                  0
RestaurantsPriceRange2_attribute_no_info            0
ByAppointmentOnly_attribute_False                   0
ByAppointmentOnly_attribute_True                    0
ByAppointmentOnly_attribute_no_info                 0
BestNightsSunday_attribute_False                    0
BestNightsSunday_attribute_True                     0
BestNightsSunday_attribute_no_info                  0
AmbienceTrendy_attribute_False                      0
AmbienceTrendy_attribute_True                       0
AmbienceTrendy_attribute_no_info                    0
GoodForKids_attribute_False                         0
GoodForKids_attribute_True                          0
GoodForKids_attribute_no_info                       0
CoatCheck_attribute_False                           0
CoatCheck_attribute_True                            0
CoatCheck_attribute_no_info                         0
RestaurantsTableService_attribute_False             0
RestaurantsTableService_attribute_True              0
RestaurantsTableService_attribute_no_info           0
DietaryRestrictionsVegan_attribute_False            0
DietaryRestrictionsVegan_attribute_no_info          0
BusinessParkingValet_attribute_False                0
BusinessParkingValet_attribute_True                 0
BusinessParkingValet_attribute_no_info              0
Corkage_attribute_False                             0
Corkage_attribute_True                              0
Corkage_attribute_no_info                           0
Music_attribute_no_info                             0
GoodForMealBreakfast_attribute_False                0
GoodForMealBreakfast_attribute_True                 0
GoodForMealBreakfast_attribute_no_info              0
AmbienceDivey_attribute_False                       0
AmbienceDivey_attribute_True                        0
AmbienceDivey_attribute_no_info                     0
DietaryRestrictionsSoy-free_attribute_False         0
DietaryRestrictionsSoy-free_attribute_no_info       0
WheelchairAccessible_attribute_False                0
WheelchairAccessible_attribute_True                 0
WheelchairAccessible_attribute_no_info              0
DietaryRestrictionsHalal_attribute_False            0
DietaryRestrictionsHalal_attribute_no_info          0
RestaurantsTakeOut_attribute_False                  0
RestaurantsTakeOut_attribute_True                   0
RestaurantsTakeOut_attribute_no_info                0
GoodForMealDessert_attribute_False                  0
GoodForMealDessert_attribute_True                   0
GoodForMealDessert_attribute_no_info                0
DietaryRestrictionsGluten-free_attribute_True       0
DietaryRestrictionsGluten-free_attribute_no_info    0
BestNightsWednesday_attribute_False                 0
BestNightsWednesday_attribute_True                  0
BestNightsWednesday_attribute_no_info               0
GoodForMealLatenight_attribute_False                0
GoodForMealLatenight_attribute_True                 0
GoodForMealLatenight_attribute_no_info              0
BestNightsSaturday_attribute_False                  0
BestNightsSaturday_attribute_True                   0
BestNightsSaturday_attribute_no_info                0
MusicLive_attribute_False                           0
MusicLive_attribute_True                            0
MusicLive_attribute_no_info                         0
MusicNo_music_attribute_False                       0
MusicNo_music_attribute_no_info                     0
BusinessParkingLot_attribute_False                  0
BusinessParkingLot_attribute_True                   0
BusinessParkingLot_attribute_no_info                0
AcceptsInsurance_attribute_False                    0
AcceptsInsurance_attribute_no_info                  0
AmbienceCasual_attribute_False                      0
AmbienceCasual_attribute_True                       0
AmbienceCasual_attribute_no_info                    0
HappyHour_attribute_False                           0
HappyHour_attribute_True                            0
HappyHour_attribute_no_info                         0
GoodForMealDinner_attribute_False                   0
GoodForMealDinner_attribute_True                    0
GoodForMealDinner_attribute_no_info                 0
MusicBackground_music_attribute_False               0
MusicBackground_music_attribute_True                0
MusicBackground_music_attribute_no_info             0
MusicKaraoke_attribute_False                        0
MusicKaraoke_attribute_True                         0
MusicKaraoke_attribute_no_info                      0
BusinessParkingValidated_attribute_False            0
BusinessParkingValidated_attribute_True             0
BusinessParkingValidated_attribute_no_info          0
WiFi_attribute_free                                 0
WiFi_attribute_no                                   0
WiFi_attribute_no_info                              0
WiFi_attribute_paid                                 0
DietaryRestrictionsKosher_attribute_False           0
DietaryRestrictionsKosher_attribute_no_info         0
Open24Hours_attribute_False                         0
Open24Hours_attribute_no_info                       0
Ambience_attribute_no_info                          0
GoodForMeal_attribute_no_info                       0
BusinessParking_attribute_no_info                   0
MusicVideo_attribute_False                          0
MusicVideo_attribute_True                           0
MusicVideo_attribute_no_info                        0
Alcohol_attribute_beer_and_wine                     0
Alcohol_attribute_full_bar                          0
Alcohol_attribute_no_info                           0
Alcohol_attribute_none                              0
DietaryRestrictionsVegetarian_attribute_False       0
DietaryRestrictionsVegetarian_attribute_no_info     0
BusinessAcceptsBitcoin_attribute_False              0
BusinessAcceptsBitcoin_attribute_True               0
BusinessAcceptsBitcoin_attribute_no_info            0
BYOB_attribute_False                                0
BYOB_attribute_True                                 0
BYOB_attribute_no_info                              0
AmbienceClassy_attribute_False                      0
AmbienceClassy_attribute_True                       0
AmbienceClassy_attribute_no_info                    0
Smoking_attribute_no                                0
Smoking_attribute_no_info                           0
Smoking_attribute_outdoor                           0
Smoking_attribute_yes                               0
BikeParking_attribute_False                         0
BikeParking_attribute_True                          0
BikeParking_attribute_no_info                       0
MusicDj_attribute_False                             0
MusicDj_attribute_True                              0
MusicDj_attribute_no_info                           0
BestNightsFriday_attribute_False                    0
BestNightsFriday_attribute_True                     0
BestNightsFriday_attribute_no_info                  0
DogsAllowed_attribute_False                         0
DogsAllowed_attribute_True                          0
DogsAllowed_attribute_no_info                       0
AgesAllowed_attribute_21plus                        0
AgesAllowed_attribute_allages                       0
AgesAllowed_attribute_no_info                       0
AmbienceTouristy_attribute_False                    0
AmbienceTouristy_attribute_True                     0
AmbienceTouristy_attribute_no_info                  0
AmbienceUpscale_attribute_False                     0
AmbienceUpscale_attribute_True                      0
AmbienceUpscale_attribute_no_info                   0
OutdoorSeating_attribute_False                      0
OutdoorSeating_attribute_True                       0
OutdoorSeating_attribute_no_info                    0
MusicJukebox_attribute_False                        0
MusicJukebox_attribute_True                         0
MusicJukebox_attribute_no_info                      0
BusinessParkingStreet_attribute_False               0
BusinessParkingStreet_attribute_True                0
BusinessParkingStreet_attribute_no_info             0
RestaurantsAttire_attribute_casual                  0
RestaurantsAttire_attribute_dressy                  0
RestaurantsAttire_attribute_formal                  0
RestaurantsAttire_attribute_no_info                 0
RestaurantsReservations_attribute_False             0
RestaurantsReservations_attribute_True              0
RestaurantsReservations_attribute_no_info           0
GoodForDancing_attribute_False                      0
GoodForDancing_attribute_True                       0
GoodForDancing_attribute_no_info                    0
HasTV_attribute_False                               0
HasTV_attribute_True                                0
HasTV_attribute_no_info                             0
BestNightsTuesday_attribute_False                   0
BestNightsTuesday_attribute_True                    0
BestNightsTuesday_attribute_no_info                 0
BusinessAcceptsCreditCards_attribute_False          0
BusinessAcceptsCreditCards_attribute_True           0
BusinessAcceptsCreditCards_attribute_no_info        0
BestNights_attribute_no_info                        0
RestaurantsGoodForGroups_attribute_False            0
RestaurantsGoodForGroups_attribute_True             0
RestaurantsGoodForGroups_attribute_no_info          0
GoodForMealLunch_attribute_False                    0
GoodForMealLunch_attribute_True                     0
GoodForMealLunch_attribute_no_info                  0
RestaurantsDelivery_attribute_False                 0
RestaurantsDelivery_attribute_True                  0
RestaurantsDelivery_attribute_no_info               0
Caters_attribute_False                              0
Caters_attribute_True                               0
Caters_attribute_no_info                            0
BYOBCorkage_attribute_no                            0
BYOBCorkage_attribute_no_info                       0
BYOBCorkage_attribute_yes_corkage                   0
BYOBCorkage_attribute_yes_free                      0
BestNightsThursday_attribute_False                  0
BestNightsThursday_attribute_True                   0
BestNightsThursday_attribute_no_info                0
DriveThru_attribute_False                           0
DriveThru_attribute_True                            0
DriveThru_attribute_no_info                         0
BestNightsMonday_attribute_False                    0
BestNightsMonday_attribute_True                     0
BestNightsMonday_attribute_no_info                  0
review_id                                           0
user_id                                             0
stars_review                                        0
useful_review                                       0
funny_review                                        0
cool_review                                         0
date                                                0
review_count_user                                   0

In [8]:
merged.info(max_cols=500)

<class 'pandas.DataFrame'>
RangeIndex: 511138 entries, 0 to 511137
Data columns (total 388 columns):
 #    Column                                            Non-Null Count   Dtype
---   ------                                            --------------   -----
 0    business_id                                       511138 non-null  str
 1    stars_business                                    511138 non-null  float64
 2    review_count_review                               511138 non-null  int64
 3    Fuzhou_category                                   511138 non-null  int64
 4    Themed Cafes_category                             511138 non-null  int64
 5    Burmese_category                                  511138 non-null  int64
 6    Falafel_category                                  511138 non-null  int64
 7    Cafes_category                                    511138 non-null  int64
 8    Conveyor Belt Sushi_category                      511138 non-null  int64
 9    Australian_category                               511138 non-null  int64
 10   Sushi Bars_category                               511138 non-null  int64
 11   Mongolian_category                                511138 non-null  int64
 12   New Mexican Cuisine_category                      511138 non-null  int64
 13   Poutineries_category                              511138 non-null  int64
 14   Ethiopian_category                                511138 non-null  int64
 15   Hong Kong Style Cafe_category                     511138 non-null  int64
 16   Cafeteria_category                                511138 non-null  int64
 17   Chicken Shop_category                             511138 non-null  int64
 18   Vegetarian_category                               511138 non-null  int64
 19   Asian Fusion_category                             511138 non-null  int64
 20   Pan Asian_category                                511138 non-null  int64
 21   Dinner Theater_category                           511138 non-null  int64
 22   Hawaiian_category                                 511138 non-null  int64
 23   Fish & Chips_category                             511138 non-null  int64
 24   French_category                                   511138 non-null  int64
 25   Filipino_category                                 511138 non-null  int64
 26   Seafood_category                                  511138 non-null  int64
 27   Szechuan_category                                 511138 non-null  int64
 28   Modern European_category                          511138 non-null  int64
 29   Himalayan/Nepalese_category                       511138 non-null  int64
 30   Senegalese_category                               511138 non-null  int64
 31   Portuguese_category                               511138 non-null  int64
 32   Delis_category                                    511138 non-null  int64
 33   Vegan_category                                    511138 non-null  int64
 34   Spanish_category                                  511138 non-null  int64
 35   Uzbek_category                                    511138 non-null  int64
 36   Iberian_category                                  511138 non-null  int64
 37   Steakhouses_category                              511138 non-null  int64
 38   Italian_category                                  511138 non-null  int64
 39   Trinidadian_category                              511138 non-null  int64
 40   Lebanese_category                                 511138 non-null  int64
 41   Wraps_category                                    511138 non-null  int64
 42   Bangladeshi_category                              511138 non-null  int64
 43   Diners_category                                   511138 non-null  int64
 44   Tapas Bars_category                               511138 non-null  int64
 45   Israeli_category                                  511138 non-null  int64
 46   Pizza_category                                    511138 non-null  int64
 47   Hainan_category                                   511138 non-null  int64
 48   Korean_category                                   511138 non-null  int64
 49   Tapas/Small Plates_category                       511138 non-null  int64
 50   Russian_category                                  511138 non-null  int64
 51   Afghan_category                                   511138 non-null  int64
 52   Mexican_category                                  511138 non-null  int64
 53   Live/Raw Food_category                            511138 non-null  int64
 54   Greek_category                                    511138 non-null  int64
 55   Teppanyaki_category                               511138 non-null  int64
 56   Polish_category                                   511138 non-null  int64
 57   Hot Pot_category                                  511138 non-null  int64
 58   Hot Dogs_category                                 511138 non-null  int64
 59   Hungarian_category                                511138 non-null  int64
 60   Indian_category                                   511138 non-null  int64
 61   Food Stands_category                              511138 non-null  int64
 62   German_category                                   511138 non-null  int64
 63   Southern_category                                 511138 non-null  int64
 64   Indonesian_category                               511138 non-null  int64
 65   African_category                                  511138 non-null  int64
 66   Sardinian_category                                511138 non-null  int64
 67   Buffets_category                                  511138 non-null  int64
 68   Cambodian_category                                511138 non-null  int64
 69   Waffles_category                                  511138 non-null  int64
 70   Sandwiches_category                               511138 non-null  int64
 71   Chinese_category                                  511138 non-null  int64
 72   Dominican_category                                511138 non-null  int64
 73   Barbeque_category                                 511138 non-null  int64
 74   Salad_category                                    511138 non-null  int64
 75   Ukrainian_category                                511138 non-null  int64
 76   Vietnamese_category                               511138 non-null  int64
 77   Soul Food_category                                511138 non-null  int64
 78   Supper Clubs_category                             511138 non-null  int64
 79   Gluten-Free_category                              511138 non-null  int64
 80   Soup_category                                     511138 non-null  int64
 81   Gastropubs_category                               511138 non-null  int64
 82   Tex-Mex_category                                  511138 non-null  int64
 83   Kebab_category                                    511138 non-null  int64
 84   Tacos_category                                    511138 non-null  int64
 85   Scandinavian_category                             511138 non-null  int64
 86   Food Court_category                               511138 non-null  int64
 87   Irish_category                                    511138 non-null  int64
 88   Cajun/Creole_category                             511138 non-null  int64
 89   Armenian_category                                 511138 non-null  int64
 90   Laotian_category                                  511138 non-null  int64
 91   Comfort Food_category                             511138 non-null  int64
 92   Cantonese_category                                511138 non-null  int64
 93   Brasseries_category                               511138 non-null  int64
 94   Kosher_category                                   511138 non-null  int64
 95   Haitian_category                                  511138 non-null  int64
 96   Dim Sum_category                                  511138 non-null  int64
 97   Cuban_category                                    511138 non-null  int64
 98   Chicken Wings_category                            511138 non-null  int64
 99   Colombian_category                                511138 non-null  int64
 100  Peruvian_category                                 511138 non-null  int64
 101  Basque_category                                   511138 non-null  int64
 102  Mediterranean_category                            511138 non-null  int64
 103  Honduran_category                                 511138 non-null  int64
 104  Ramen_category                                    511138 non-null  int64
 105  Pop-Up Restaurants_category                       511138 non-null  int64
 106  Fast Food_category                                511138 non-null  int64
 107  Latin American_category                           511138 non-null  int64
 108  Persian/Iranian_category                          511138 non-null  int64
 109  Puerto Rican_category                             511138 non-null  int64
 110  Brazilian_category                                511138 non-null  int64
 111  Argentine_category                                511138 non-null  int64
 112  Creperies_category                                511138 non-null  int64
 113  Sicilian_category                                 511138 non-null  int64
 114  Pakistani_category                                511138 non-null  int64
 115  Georgian_category                                 511138 non-null  int64
 116  Belgian_category                                  511138 non-null  int64
 117  Noodles_category                                  511138 non-null  int64
 118  Caribbean_category                                511138 non-null  int64
 119  Singaporean_category                              511138 non-null  int64
 120  Breakfast & Brunch_category                       511138 non-null  int64
 121  Burgers_category                                  511138 non-null  int64
 122  South African_category                            511138 non-null  int64
 123  Venezuelan_category                               511138 non-null  int64
 124  Halal_category                                    511138 non-null  int64
 125  Turkish_category                                  511138 non-null  int64
 126  Thai_category                                     511138 non-null  int64
 127  British_category                                  511138 non-null  int64
 128  Japanese_category                                 511138 non-null  int64
 129  Shanghainese_category                             511138 non-null  int64
 130  Middle Eastern_category                           511138 non-null  int64
 131  Salvadoran_category                               511138 non-null  int64
 132  Izakaya_category                                  511138 non-null  int64
 133  American (New)_category                           511138 non-null  int64
 134  Malaysian_category                                511138 non-null  int64
 135  Moroccan_category                                 511138 non-null  int64
 136  Taiwanese_category                                511138 non-null  int64
 137  Japanese Curry_category                           511138 non-null  int64
 138  American (Traditional)_category                   511138 non-null  int64
 139  Cheesesteaks_category                             511138 non-null  int64
 140  AmbienceRomantic_attribute_False                  511138 non-null  int64
 141  AmbienceRomantic_attribute_True                   511138 non-null  int64
 142  AmbienceRomantic_attribute_no_info                511138 non-null  int64
 143  AmbienceHipster_attribute_False                   511138 non-null  int64
 144  AmbienceHipster_attribute_True                    511138 non-null  int64
 145  AmbienceHipster_attribute_no_info                 511138 non-null  int64
 146  NoiseLevel_attribute_average                      511138 non-null  int64
 147  NoiseLevel_attribute_loud                         511138 non-null  int64
 148  NoiseLevel_attribute_no_info                      511138 non-null  int64
 149  NoiseLevel_attribute_quiet                        511138 non-null  int64
 150  NoiseLevel_attribute_very_loud                    511138 non-null  int64
 151  RestaurantsCounterService_attribute_True          511138 non-null  int64
 152  RestaurantsCounterService_attribute_no_info       511138 non-null  int64
 153  DietaryRestrictionsDairy-free_attribute_False     511138 non-null  int64
 154  DietaryRestrictionsDairy-free_attribute_no_info   511138 non-null  int64
 155  AmbienceIntimate_attribute_False                  511138 non-null  int64
 156  AmbienceIntimate_attribute_True                   511138 non-null  int64
 157  AmbienceIntimate_attribute_no_info                511138 non-null  int64
 158  GoodForMealBrunch_attribute_False                 511138 non-null  int64
 159  GoodForMealBrunch_attribute_True                  511138 non-null  int64
 160  GoodForMealBrunch_attribute_no_info               511138 non-null  int64
 161  BusinessParkingGarage_attribute_False             511138 non-null  int64
 162  BusinessParkingGarage_attribute_True              511138 non-null  int64
 163  BusinessParkingGarage_attribute_no_info           511138 non-null  int64
 164  RestaurantsPriceRange2_attribute_1                511138 non-null  int64
 165  RestaurantsPriceRange2_attribute_2                511138 non-null  int64
 166  RestaurantsPriceRange2_attribute_3                511138 non-null  int64
 167  RestaurantsPriceRange2_attribute_4                511138 non-null  int64
 168  RestaurantsPriceRange2_attribute_no_info          511138 non-null  int64
 169  ByAppointmentOnly_attribute_False                 511138 non-null  int64
 170  ByAppointmentOnly_attribute_True                  511138 non-null  int64
 171  ByAppointmentOnly_attribute_no_info               511138 non-null  int64
 172  BestNightsSunday_attribute_False                  511138 non-null  int64
 173  BestNightsSunday_attribute_True                   511138 non-null  int64
 174  BestNightsSunday_attribute_no_info                511138 non-null  int64
 175  AmbienceTrendy_attribute_False                    511138 non-null  int64
 176  AmbienceTrendy_attribute_True                     511138 non-null  int64
 177  AmbienceTrendy_attribute_no_info                  511138 non-null  int64
 178  GoodForKids_attribute_False                       511138 non-null  int64
 179  GoodForKids_attribute_True                        511138 non-null  int64
 180  GoodForKids_attribute_no_info                     511138 non-null  int64
 181  CoatCheck_attribute_False                         511138 non-null  int64
 182  CoatCheck_attribute_True                          511138 non-null  int64
 183  CoatCheck_attribute_no_info                       511138 non-null  int64
 184  RestaurantsTableService_attribute_False           511138 non-null  int64
 185  RestaurantsTableService_attribute_True            511138 non-null  int64
 186  RestaurantsTableService_attribute_no_info         511138 non-null  int64
 187  DietaryRestrictionsVegan_attribute_False          511138 non-null  int64
 188  DietaryRestrictionsVegan_attribute_no_info        511138 non-null  int64
 189  BusinessParkingValet_attribute_False              511138 non-null  int64
 190  BusinessParkingValet_attribute_True               511138 non-null  int64
 191  BusinessParkingValet_attribute_no_info            511138 non-null  int64
 192  Corkage_attribute_False                           511138 non-null  int64
 193  Corkage_attribute_True                            511138 non-null  int64
 194  Corkage_attribute_no_info                         511138 non-null  int64
 195  Music_attribute_no_info                           511138 non-null  int64
 196  GoodForMealBreakfast_attribute_False              511138 non-null  int64
 197  GoodForMealBreakfast_attribute_True               511138 non-null  int64
 198  GoodForMealBreakfast_attribute_no_info            511138 non-null  int64
 199  AmbienceDivey_attribute_False                     511138 non-null  int64
 200  AmbienceDivey_attribute_True                      511138 non-null  int64
 201  AmbienceDivey_attribute_no_info                   511138 non-null  int64
 202  DietaryRestrictionsSoy-free_attribute_False       511138 non-null  int64
 203  DietaryRestrictionsSoy-free_attribute_no_info     511138 non-null  int64
 204  WheelchairAccessible_attribute_False              511138 non-null  int64
 205  WheelchairAccessible_attribute_True               511138 non-null  int64
 206  WheelchairAccessible_attribute_no_info            511138 non-null  int64
 207  DietaryRestrictionsHalal_attribute_False          511138 non-null  int64
 208  DietaryRestrictionsHalal_attribute_no_info        511138 non-null  int64
 209  RestaurantsTakeOut_attribute_False                511138 non-null  int64
 210  RestaurantsTakeOut_attribute_True                 511138 non-null  int64
 211  RestaurantsTakeOut_attribute_no_info              511138 non-null  int64
 212  GoodForMealDessert_attribute_False                511138 non-null  int64
 213  GoodForMealDessert_attribute_True                 511138 non-null  int64
 214  GoodForMealDessert_attribute_no_info              511138 non-null  int64
 215  DietaryRestrictionsGluten-free_attribute_True     511138 non-null  int64
 216  DietaryRestrictionsGluten-free_attribute_no_info  511138 non-null  int64
 217  BestNightsWednesday_attribute_False               511138 non-null  int64
 218  BestNightsWednesday_attribute_True                511138 non-null  int64
 219  BestNightsWednesday_attribute_no_info             511138 non-null  int64
 220  GoodForMealLatenight_attribute_False              511138 non-null  int64
 221  GoodForMealLatenight_attribute_True               511138 non-null  int64
 222  GoodForMealLatenight_attribute_no_info            511138 non-null  int64
 223  BestNightsSaturday_attribute_False                511138 non-null  int64
 224  BestNightsSaturday_attribute_True                 511138 non-null  int64
 225  BestNightsSaturday_attribute_no_info              511138 non-null  int64
 226  MusicLive_attribute_False                         511138 non-null  int64
 227  MusicLive_attribute_True                          511138 non-null  int64
 228  MusicLive_attribute_no_info                       511138 non-null  int64
 229  MusicNo_music_attribute_False                     511138 non-null  int64
 230  MusicNo_music_attribute_no_info                   511138 non-null  int64
 231  BusinessParkingLot_attribute_False                511138 non-null  int64
 232  BusinessParkingLot_attribute_True                 511138 non-null  int64
 233  BusinessParkingLot_attribute_no_info              511138 non-null  int64
 234  AcceptsInsurance_attribute_False                  511138 non-null  int64
 235  AcceptsInsurance_attribute_no_info                511138 non-null  int64
 236  AmbienceCasual_attribute_False                    511138 non-null  int64
 237  AmbienceCasual_attribute_True                     511138 non-null  int64
 238  AmbienceCasual_attribute_no_info                  511138 non-null  int64
 239  HappyHour_attribute_False                         511138 non-null  int64
 240  HappyHour_attribute_True                          511138 non-null  int64
 241  HappyHour_attribute_no_info                       511138 non-null  int64
 242  GoodForMealDinner_attribute_False                 511138 non-null  int64
 243  GoodForMealDinner_attribute_True                  511138 non-null  int64
 244  GoodForMealDinner_attribute_no_info               511138 non-null  int64
 245  MusicBackground_music_attribute_False             511138 non-null  int64
 246  MusicBackground_music_attribute_True              511138 non-null  int64
 247  MusicBackground_music_attribute_no_info           511138 non-null  int64
 248  MusicKaraoke_attribute_False                      511138 non-null  int64

In [9]:
timestamp_format = "%Y-%m-%d %H:%M:%S"
merged["date"] = merged["date"].apply(lambda x: datetime.datetime.strptime(x, timestamp_format))
merged["yelping_since"] = merged["yelping_since"].apply(lambda x: datetime.datetime.strptime(x, timestamp_format))
merged["date"] = (merged["date"] - pd.Timestamp("1970-01-01")) // pd.Timedelta('1s')
merged["yelping_since"] = (merged["yelping_since"] - pd.Timestamp("1970-01-01")) // pd.Timedelta('1s')

In [10]:
merged_no_ids = merged.drop(labels=["review_id", "user_id", "business_id"], axis=1)
display(merged_no_ids)

,stars_business,review_count_review,Fuzhou_category,Themed Cafes_category,Burmese_category,Falafel_category,Cafes_category,Conveyor Belt Sushi_category,Australian_category,Sushi Bars_category,...,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos,number_of_friends
0,4.0,80,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
1,4.0,80,0,0,0,0,0,0,0,0,...,6,1,0,11,28,46,46,26,20,186
2,4.0,80,0,0,0,0,0,0,0,0,...,0,0,0,3,8,2,2,5,0,18
3,4.0,80,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
4,4.0,80,0,0,0,0,0,0,0,0,...,0,1,4,24,51,35,35,13,5,141
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511133,4.5,35,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
511134,4.5,35,0,0,0,0,0,0,0,0,...,0,0,0,3,3,4,4,1,3,6
511135,4.5,35,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
511136,4.5,35,0,0,0,0,0,0,0,0,...,0,0,0,5,0,0,0,0,0,77
511137,4.5,35,0,0,0,0,0,0,0,0,...,0,0,0,6,2,4,4,2,0,79

In [11]:
merged_only_ids = merged[["review_id", "user_id", "business_id"]]
merged_only_ids

                     review_id                 user_id             business_id
0       BXQcBN0iAi1lAUxibGLFzA  6_SpY41LIHZuIaiDs5FMKA  MTSW4McQd7CbVtyjqoe9mw
1       uduvUCvi9w3T2bSGivCfXg  tCXElwhzekJEH6QJe3xs7Q  MTSW4McQd7CbVtyjqoe9mw
2       a0vwPOqDXXZuJkbBW2356g  WqfKtI-aGMmvbA9pPUxNQQ  MTSW4McQd7CbVtyjqoe9mw
3       MKNp_CdR2k2202-c8GN5Dw  3-1va0IQfK-9tUMzfHWfTA  MTSW4McQd7CbVtyjqoe9mw
4       D1GisLDPe84Rrk_R4X2brQ  EouCKoDfzaVG0klEgdDvCQ  MTSW4McQd7CbVtyjqoe9mw
...                        ...                     ...                     ...
511133  qBcwQEQPnLxjkw-xbUIF4Q  6nF5PT1c0dF6EpOgQdF2tw  WnT9NIzQgLlILjPT0kEcsQ
511134  G8fbysnUAUmqq1XWTjMQ4Q  1M78_w4J9f5S8xmUVYyxdQ  WnT9NIzQgLlILjPT0kEcsQ
511135  JKiy0aeyGd3KmXN7uRPFLw  B7TD5yTemGv50y4wM2EVNA  WnT9NIzQgLlILjPT0kEcsQ
511136  JITY01bGbdsiUBznLz9rdg  HI8QwhpeP_ZRY5JZy11VDw  WnT9NIzQgLlILjPT0kEcsQ
511137  VzKF0662H2NLbpbmGv20Ug  CmR9s-2zH20UkmUt5Qwqnw  WnT9NIzQgLlILjPT0kEcsQ

[511138 rows x 3 columns]

In [12]:
scaler = MinMaxScaler(feature_range=(0, 1))
scaler.fit(merged_no_ids)
merged_no_ids = pd.DataFrame(scaler.transform(merged_no_ids), columns=merged_no_ids.columns)
display(merged_no_ids)

,stars_business,review_count_review,Fuzhou_category,Themed Cafes_category,Burmese_category,Falafel_category,Cafes_category,Conveyor Belt Sushi_category,Australian_category,Sushi Bars_category,...,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos,number_of_friends
0,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000063,0.000000,0.000000
1,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000852,0.000336,0.000000,0.000186,0.000277,0.000921,0.000921,0.001632,0.000356,0.012338
2,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000051,0.000079,0.000040,0.000040,0.000314,0.000000,0.001134
3,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000200
4,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000336,0.001534,0.000407,0.000504,0.000700,0.000700,0.000816,0.000089,0.009337
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511133,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000010,0.000000,0.000000,0.000000,0.000000,0.000000
511134,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000051,0.000030,0.000080,0.000080,0.000063,0.000053,0.000333
511135,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
511136,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000085,0.000000,0.000000,0.000000,0.000000,0.000000,0.005069
511137,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000102,0.000020,0.000080,0.000080,0.000126,0.000000,0.005202

In [13]:
merged_no_ids_copy = merged_no_ids.copy()
merged_no_ids_copy = merged_no_ids_copy.drop(columns=["review_count_user", "yelping_since", "useful_user", "funny_user", "cool_user", "fans", "average_stars", "compliment_hot", "compliment_more", "compliment_profile", "compliment_cute", "compliment_list", "compliment_note", "compliment_plain", "compliment_cool", "compliment_funny", "compliment_writer", "compliment_photos", "number_of_friends", "useful_review", "funny_review", "cool_review", "stars_review"])
merged_no_ids_copy

,stars_business,review_count_review,Fuzhou_category,Themed Cafes_category,Burmese_category,Falafel_category,Cafes_category,Conveyor Belt Sushi_category,Australian_category,Sushi Bars_category,...,BestNightsThursday_attribute_False,BestNightsThursday_attribute_True,BestNightsThursday_attribute_no_info,DriveThru_attribute_False,DriveThru_attribute_True,DriveThru_attribute_no_info,BestNightsMonday_attribute_False,BestNightsMonday_attribute_True,BestNightsMonday_attribute_no_info,date
0,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.547730
1,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.510133
2,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.513276
3,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.783217
4,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.513282
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511133,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.933705
511134,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.932890
511135,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.951791
511136,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.943997
511137,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.877333

In [14]:
merged = merged_only_ids.join(merged_no_ids)
display(merged)

,review_id,user_id,business_id,stars_business,review_count_review,Fuzhou_category,Themed Cafes_category,Burmese_category,Falafel_category,Cafes_category,...,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos,number_of_friends
0,BXQcBN0iAi1lAUxibGLFzA,6_SpY41LIHZuIaiDs5FMKA,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000063,0.000000,0.000000
1,uduvUCvi9w3T2bSGivCfXg,tCXElwhzekJEH6QJe3xs7Q,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.000852,0.000336,0.000000,0.000186,0.000277,0.000921,0.000921,0.001632,0.000356,0.012338
2,a0vwPOqDXXZuJkbBW2356g,WqfKtI-aGMmvbA9pPUxNQQ,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000051,0.000079,0.000040,0.000040,0.000314,0.000000,0.001134
3,MKNp_CdR2k2202-c8GN5Dw,3-1va0IQfK-9tUMzfHWfTA,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000200
4,D1GisLDPe84Rrk_R4X2brQ,EouCKoDfzaVG0klEgdDvCQ,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000336,0.001534,0.000407,0.000504,0.000700,0.000700,0.000816,0.000089,0.009337
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511133,qBcwQEQPnLxjkw-xbUIF4Q,6nF5PT1c0dF6EpOgQdF2tw,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000010,0.000000,0.000000,0.000000,0.000000,0.000000
511134,G8fbysnUAUmqq1XWTjMQ4Q,1M78_w4J9f5S8xmUVYyxdQ,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000051,0.000030,0.000080,0.000080,0.000063,0.000053,0.000333
511135,JKiy0aeyGd3KmXN7uRPFLw,B7TD5yTemGv50y4wM2EVNA,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
511136,JITY01bGbdsiUBznLz9rdg,HI8QwhpeP_ZRY5JZy11VDw,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000085,0.000000,0.000000,0.000000,0.000000,0.000000,0.005069
511137,VzKF0662H2NLbpbmGv20Ug,CmR9s-2zH20UkmUt5Qwqnw,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000102,0.000020,0.000080,0.000080,0.000126,0.000000,0.005202

In [15]:
merged_copy = merged_only_ids.join(merged_no_ids_copy)
display(merged_copy)

,review_id,user_id,business_id,stars_business,review_count_review,Fuzhou_category,Themed Cafes_category,Burmese_category,Falafel_category,Cafes_category,...,BestNightsThursday_attribute_False,BestNightsThursday_attribute_True,BestNightsThursday_attribute_no_info,DriveThru_attribute_False,DriveThru_attribute_True,DriveThru_attribute_no_info,BestNightsMonday_attribute_False,BestNightsMonday_attribute_True,BestNightsMonday_attribute_no_info,date
0,BXQcBN0iAi1lAUxibGLFzA,6_SpY41LIHZuIaiDs5FMKA,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.547730
1,uduvUCvi9w3T2bSGivCfXg,tCXElwhzekJEH6QJe3xs7Q,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.510133
2,a0vwPOqDXXZuJkbBW2356g,WqfKtI-aGMmvbA9pPUxNQQ,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.513276
3,MKNp_CdR2k2202-c8GN5Dw,3-1va0IQfK-9tUMzfHWfTA,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.783217
4,D1GisLDPe84Rrk_R4X2brQ,EouCKoDfzaVG0klEgdDvCQ,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.513282
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511133,qBcwQEQPnLxjkw-xbUIF4Q,6nF5PT1c0dF6EpOgQdF2tw,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.933705
511134,G8fbysnUAUmqq1XWTjMQ4Q,1M78_w4J9f5S8xmUVYyxdQ,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.932890
511135,JKiy0aeyGd3KmXN7uRPFLw,B7TD5yTemGv50y4wM2EVNA,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.951791
511136,JITY01bGbdsiUBznLz9rdg,HI8QwhpeP_ZRY5JZy11VDw,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.943997
511137,VzKF0662H2NLbpbmGv20Ug,CmR9s-2zH20UkmUt5Qwqnw,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.877333

In [16]:
sequence_length = 5

In [17]:
indexes = merged.value_counts("user_id")[(merged.value_counts("user_id") >= sequence_length)].index
indexes

Index(['ET8n-r7glWYqZhuR6GcdNw', 'vFd8aBLg1kFcd0kCkoi-xw',
       '_BcWyKQL16ndpBdggh2kNA', 'bJ5FtCtZX3ZZacz2_2PJjA',
       '0DB3Irpf_ETVXu_Ou9vPow', 'kauJmG3ZiA-m5u0nPrjb4g',
       'WO6L5yMX5LEeJuMNMjerRQ', '8EMU7d4pCkdqUnvlIW40CA',
       'LnFIWZM_l__4t8Qxj3pnOg', 'OLGQ7alK4VKl3YdQk6UF5g',
       ...
       'GQgH--hxKJisGmfsKj0xDA', 'Zy8NOrdYcTaKJxbfdM0kHQ',
       'nh6ArLduHi_53eMPMW0fgw', 'OxaqY6xoDhFFxyICEX4QQQ',
       'EWLuooWEKiGZlxl3jccVyA', 'LU0KeX-SHEFhI77xqDueoA',
       'MKkCT6R15R2nrURE6VTOgA', 'kJModxtvXak455L9xo9xXw',
       'RhoZYeIa3tP0nTEitoNFzA', 'knE5x-gQ6ALjcXHpSkpkVw'],
      dtype='str', name='user_id', length=19902)

In [18]:
def split_to_sequences(df, user_indices, sequence_length):
    user_sequences = []
    for user_id in user_indices:
        user_df = df[df["user_id"] == user_id].sort_values("date")
        # print("zaciatok", len(user_df))

        while len(user_df) >= sequence_length:
            user_sequences.append(user_df.iloc[:sequence_length])
            user_df = user_df.iloc[sequence_length:]
        # print("end", len(user_df))
    return user_sequences

In [20]:
user_sequences = split_to_sequences(merged, user_indices=indexes, sequence_length=5)
print("user_sequences split")
user_sequences_copy = split_to_sequences(merged_copy, user_indices=indexes, sequence_length=5)
print("user_sequences_copy split")

user_sequences split
user_sequences_copy split

In [ ]:
# user_sequences = []
# for user_id in indexes:
#     user_df = merged[merged["user_id"] == user_id].sort_values("date")
#     # print("zaciatok", len(user_df))
# 
#     while len(user_df) >= sequence_length:
#         user_sequences.append(user_df.iloc[:sequence_length])
#         user_df = user_df.iloc[sequence_length:]
#     # print("end", len(user_df))

zaciatok 610
end 0
zaciatok 447
end 2
zaciatok 441
end 1
zaciatok 375
end 0
zaciatok 357
end 2
zaciatok 343
end 3
zaciatok 332
end 2
zaciatok 331
end 1
zaciatok 277
end 2
zaciatok 272
end 2
zaciatok 271
end 1
zaciatok 261
end 1
zaciatok 260
end 0
zaciatok 260
end 0
zaciatok 246
end 1
zaciatok 241
end 1
zaciatok 229
end 4
zaciatok 229
end 4
zaciatok 227
end 2
zaciatok 226
end 1
zaciatok 225
end 0
zaciatok 220
end 0
zaciatok 215
end 0
zaciatok 214
end 4
zaciatok 211
end 1
zaciatok 203
end 3
zaciatok 200
end 0
zaciatok 200
end 0
zaciatok 199
end 4
zaciatok 197
end 2
zaciatok 197
end 2
zaciatok 196
end 1
zaciatok 195
end 0
zaciatok 181
end 1
zaciatok 178
end 3
zaciatok 178
end 3
zaciatok 176
end 1
zaciatok 176
end 1
zaciatok 172
end 2
zaciatok 170
end 0
zaciatok 170
end 0
zaciatok 169
end 4
zaciatok 167
end 2
zaciatok 166
end 1
zaciatok 166
end 1
zaciatok 166
end 1
zaciatok 165
end 0
zaciatok 163
end 3
zaciatok 161
end 1
zaciatok 161
end 1
zaciatok 159
end 4
zaciatok 159
end 4
zaciatok 159
end 4
zaciatok 158
end 3
zaciatok 158
end 3
zaciatok 157
end 2
zaciatok 156
end 1
zaciatok 156
end 1
zaciatok 155
end 0
zaciatok 154
end 4
zaciatok 153
end 3
zaciatok 152
end 2
zaciatok 152
end 2
zaciatok 151
end 1
zaciatok 150
end 0
zaciatok 148
end 3
zaciatok 148
end 3
zaciatok 148
end 3
zaciatok 148
end 3
zaciatok 147
end 2
zaciatok 146
end 1
zaciatok 146
end 1
zaciatok 146
end 1
zaciatok 145
end 0
zaciatok 144
end 4
zaciatok 144
end 4
zaciatok 144
end 4
zaciatok 143
end 3
zaciatok 143
end 3
zaciatok 142
end 2
zaciatok 141
end 1
zaciatok 141
end 1
zaciatok 141
end 1
zaciatok 140
end 0
zaciatok 140
end 0
zaciatok 140
end 0
zaciatok 139
end 4
zaciatok 138
end 3
zaciatok 137
end 2
zaciatok 136
end 1
zaciatok 136
end 1
zaciatok 135
end 0
zaciatok 135
end 0
zaciatok 135
end 0
zaciatok 134
end 4
zaciatok 133
end 3
zaciatok 133
end 3
zaciatok 133
end 3
zaciatok 132
end 2
zaciatok 131
end 1
zaciatok 131
end 1
zaciatok 130
end 0
zaciatok 129
end 4
zaciatok 129
end 4
zaciatok 128
end 3
zaciatok 128
end 3
zaciatok 127
end 2
zaciatok 126
end 1
zaciatok 126
end 1
zaciatok 126
end 1
zaciatok 125
end 0
zaciatok 125
end 0
zaciatok 125
end 0
zaciatok 125
end 0
zaciatok 125
end 0
zaciatok 124
end 4
zaciatok 124
end 4
zaciatok 124
end 4
zaciatok 124
end 4
zaciatok 123
end 3
zaciatok 123
end 3
zaciatok 122
end 2
zaciatok 122
end 2
zaciatok 121
end 1
zaciatok 121
end 1
zaciatok 121
end 1
zaciatok 121
end 1
zaciatok 120
end 0
zaciatok 119
end 4
zaciatok 118
end 3
zaciatok 118
end 3
zaciatok 117
end 2
zaciatok 117
end 2
zaciatok 117
end 2
zaciatok 117
end 2
zaciatok 116
end 1
zaciatok 116
end 1
zaciatok 116
end 1
zaciatok 116
end 1
zaciatok 115
end 0
zaciatok 115
end 0
zaciatok 115
end 0
zaciatok 115
end 0
zaciatok 115
end 0
zaciatok 115
end 0
zaciatok 114
end 4
zaciatok 114
end 4
zaciatok 113
end 3
zaciatok 113
end 3
zaciatok 113
end 3
zaciatok 113
end 3
zaciatok 113
end 3
zaciatok 113
end 3
zaciatok 112
end 2
zaciatok 112
end 2
zaciatok 112
end 2
zaciatok 111
end 1
zaciatok 111
end 1
zaciatok 111
end 1
zaciatok 111
end 1
zaciatok 111
end 1
zaciatok 111
end 1
zaciatok 110
end 0
zaciatok 110
end 0
zaciatok 110
end 0
zaciatok 110
end 0
zaciatok 109
end 4
zaciatok 109
end 4
zaciatok 109
end 4
zaciatok 109
end 4
zaciatok 108
end 3
zaciatok 108
end 3
zaciatok 107
end 2
zaciatok 107
end 2
zaciatok 107
end 2
zaciatok 106
end 1
zaciatok 105
end 0
zaciatok 105
end 0
zaciatok 105
end 0
zaciatok 104
end 4
zaciatok 104
end 4
zaciatok 104
end 4
zaciatok 104
end 4
zaciatok 103
end 3
zaciatok 103
end 3
zaciatok 103
end 3
zaciatok 102
end 2
zaciatok 102
end 2
zaciatok 102
end 2
zaciatok 102
end 2
zaciatok 101
end 1
zaciatok 100
end 0
zaciatok 100
end 0
zaciatok 100
end 0
zaciatok 100
end 0
zaciatok 99
end 4
zaciatok 99
end 4
zaciatok 99
end 4
zaciatok 99
end 4
zaciatok 99
end 4
zaciatok 99
end 4
zaciatok 99
end 4
zaciatok 99
end 4
zaciatok 98
end 3
zaciatok 98
end 3
zaciatok 98
end 3
zaciatok 98
end 3
zaciatok 98
end 3
zaciatok 98
end 3
zaciatok 97
end 2
zaciatok 97
end 2
zaciatok 96
end 1
zaciatok 96
end 1
zaciatok 96
end 1
zaciatok 95
end 0
zaciatok 95
end 0
zaciatok 95
end 0
zaciatok 95
end 0
zaciatok 95
end 0
zaciatok 95
end 0
zaciatok 94
end 4
zaciatok 94
end 4
zaciatok 93
end 3
zaciatok 93
end 3
zaciatok 93
end 3
zaciatok 93
end 3
zaciatok 92
end 2
zaciatok 92
end 2
zaciatok 92
end 2
zaciatok 92
end 2
zaciatok 92
end 2
zaciatok 92
end 2
zaciatok 92
end 2
zaciatok 92
end 2
zaciatok 91
end 1
zaciatok 91
end 1
zaciatok 91
end 1
zaciatok 91
end 1
zaciatok 91
end 1
zaciatok 91
end 1
zaciatok 91
end 1
zaciatok 91
end 1
zaciatok 91
end 1
zaciatok 91
end 1
zaciatok 91
end 1
zaciatok 91
end 1
zaciatok 90
end 0
zaciatok 90
end 0
zaciatok 90
end 0
zaciatok 90
end 0
zaciatok 90
end 0
zaciatok 89
end 4
zaciatok 89
end 4
zaciatok 89
end 4
zaciatok 89
end 4
zaciatok 89
end 4
zaciatok 88
end 3
zaciatok 88
end 3
zaciatok 88
end 3
zaciatok 88
end 3
zaciatok 87
end 2
zaciatok 87
end 2
zaciatok 87
end 2
zaciatok 87
end 2
zaciatok 87
end 2
zaciatok 87
end 2
zaciatok 87
end 2
zaciatok 86
end 1
zaciatok 86
end 1
zaciatok 86
end 1
zaciatok 86
end 1
zaciatok 86
end 1
zaciatok 86
end 1
zaciatok 85
end 0
zaciatok 85
end 0
zaciatok 85
end 0
zaciatok 85
end 0
zaciatok 85
end 0
zaciatok 84
end 4
zaciatok 84
end 4
zaciatok 84
end 4
zaciatok 84
end 4
zaciatok 84
end 4
zaciatok 84
end 4
zaciatok 83
end 3
zaciatok 83
end 3
zaciatok 83
end 3
zaciatok 83
end 3
zaciatok 83
end 3
zaciatok 83
end 3
zaciatok 83
end 3
zaciatok 83
end 3
zaciatok 82
end 2
zaciatok 82
end 2
zaciatok 82
end 2
zaciatok 82
end 2
zaciatok 82
end 2
zaciatok 82
end 2
zaciatok 81
end 1
zaciatok 81
end 1
zaciatok 81
end 1
zaciatok 81
end 1
zaciatok 81
end 1
zaciatok 81
end 1
zaciatok 81
end 1
zaciatok 81
end 1
zaciatok 80
end 0
zaciatok 80
end 0
zaciatok 80
end 0
zaciatok 80
end 0
zaciatok 80
end 0
zaciatok 80
end 0
zaciatok 80
end 0
zaciatok 79
end 4
zaciatok 79
end 4
zaciatok 79
end 4
zaciatok 79
end 4
zaciatok 79
end 4
zaciatok 79
end 4
zaciatok 79
end 4
zaciatok 79
end 4
zaciatok 79
end 4
zaciatok 78
end 3
zaciatok 78
end 3
zaciatok 78
end 3
zaciatok 78
end 3
zaciatok 78
end 3
zaciatok 78
end 3
zaciatok 78
end 3
zaciatok 78
end 3
zaciatok 78
end 3
zaciatok 78
end 3
zaciatok 78
end 3
zaciatok 78
end 3
zaciatok 78
end 3
zaciatok 78
end 3
zaciatok 78
end 3
zaciatok 77
end 2
zaciatok 77
end 2
zaciatok 77
end 2
zaciatok 77
end 2
zaciatok 77
end 2
zaciatok 77
end 2
zaciatok 76
end 1
zaciatok 76
end 1
zaciatok 76
end 1
zaciatok 76
end 1
zaciatok 76
end 1
zaciatok 76
end 1
zaciatok 76
end 1
zaciatok 76
end 1
zaciatok 76
end 1
zaciatok 76
end 1
zaciatok 76
end 1
zaciatok 75
end 0
zaciatok 75
end 0
zaciatok 75
end 0
zaciatok 75
end 0
zaciatok 75
end 0
zaciatok 75
end 0
zaciatok 75
end 0
zaciatok 75
end 0
zaciatok 75
end 0
zaciatok 75
end 0
zaciatok 75
end 0
zaciatok 75
end 0
zaciatok 75
end 0
zaciatok 74
end 4
zaciatok 74
end 4
zaciatok 74
end 4
zaciatok 74
end 4
zaciatok 74
end 4
zaciatok 74
end 4
zaciatok 74
end 4
zaciatok 74
end 4
zaciatok 74
end 4
zaciatok 74
end 4
zaciatok 74
end 4
zaciatok 74
end 4
zaciatok 74
end 4
zaciatok 74
end 4
zaciatok 74
end 4
zaciatok 74
end 4
zaciatok 73
end 3
zaciatok 73
end 3
zaciatok 73
end 3
zaciatok 73
end 3
zaciatok 73
end 3
zaciatok 73
end 3
zaciatok 73
end 3
zaciatok 73
end 3
zaciatok 73
end 3
zaciatok 73
end 3
zaciatok 73
end 3
zaciatok 73
end 3
zaciatok 73
end 3
zaciatok 73
end 3
zaciatok 72
end 2
zaciatok 72
end 2
zaciatok 72
end 2
zaciatok 72
end 2
zaciatok 72
end 2
zaciatok 72
end 2
zaciatok 72
end 2
zaciatok 72
end 2
zaciatok 72
end 2
zaciatok 71
end 1
zaciatok 71
end 1
zaciatok 71
end 1
zaciatok 71
end 1
zaciatok 71
end 1
zaciatok 71
end 1
zaciatok 71
end 1
zaciatok 71
end 1
zaciatok 71
end 1
zaciatok 70
end 0
zaciatok 70
end 0
zaciatok 70
end 0
zaciatok 70
end 0
zaciatok 70
end 0
zaciatok 70
end 0
zaciatok 70
end 0
zaciatok 70
end 0
zaciatok 70
end 0
zaciatok 70
end 0
zaciatok 70
end 0
zaciatok 70
end 0
zaciatok 69
end 4
zaciatok 69
end 4
zaciatok 69
end 4
zaciatok 69
end 4
zaciatok 69
end 4
zaciatok 69
end 4
zaciatok 69
end 4
zaciatok 69
end 4
zaciatok 69
end 4
zaciatok 69
end 4
zaciatok 69
end 4
zaciatok 68
end 3
zaciatok 68
end 3
zaciatok 68
end 3
zaciatok 68
end 3
zaciatok 68
end 3
zaciatok 68
end 3
zaciatok 68
end 3
zaciatok 68
end 3
zaciatok 68
end 3
zaciatok 68
end 3
zaciatok 68
end 3
zaciatok 68
end 3
zaciatok 68
end 3
zaciatok 68
end 3
zaciatok 68
end 3
zaciatok 68
end 3
zaciatok 68
end 3
zaciatok 68
end 3
zaciatok 67
end 2
zaciatok 67
end 2
zaciatok 67
end 2
zaciatok 67
end 2
zaciatok 67
end 2
zaciatok 67
end 2
zaciatok 67
end 2
zaciatok 67
end 2
zaciatok 67
end 2
zaciatok 67
end 2
zaciatok 67
end 2
zaciatok 67
end 2
zaciatok 67
end 2
zaciatok 67
end 2
zaciatok 67
end 2
zaciatok 66
end 1
zaciatok 66
end 1
zaciatok 66
end 1
zaciatok 66
end 1
zaciatok 66
end 1
zaciatok 66
end 1
zaciatok 66
end 1
zaciatok 66
end 1
zaciatok 66
end 1
zaciatok 66
end 1
zaciatok 66
end 1
zaciatok 66
end 1
zaciatok 66
end 1
zaciatok 66
end 1
zaciatok 66
end 1
zaciatok 65
end 0
zaciatok 65
end 0
zaciatok 65
end 0
zaciatok 65
end 0
zaciatok 65
end 0
zaciatok 65
end 0
zaciatok 65
end 0
zaciatok 65
end 0
zaciatok 65
end 0
zaciatok 65
end 0
zaciatok 64
end 4
zaciatok 64
end 4
zaciatok 64
end 4
zaciatok 64
end 4
zaciatok 64
end 4
zaciatok 64
end 4
zaciatok 64
end 4
zaciatok 64
end 4
zaciatok 64
end 4
zaciatok 64
end 4
zaciatok 64
end 4
zaciatok 64
end 4
zaciatok 64
end 4
zaciatok 64
end 4
zaciatok 64
end 4
zaciatok 64
end 4
zaciatok 64
end 4
zaciatok 64
end 4
zaciatok 64
end 4
zaciatok 64
end 4
zaciatok 64
end 4
zaciatok 64
end 4
zaciatok 63
end 3
zaciatok 63
end 3
zaciatok 63
end 3
zaciatok 63
end 3
zaciatok 63
end 3
zaciatok 63
end 3
zaciatok 63
end 3
zaciatok 63
end 3
zaciatok 63
end 3
zaciatok 63
end 3
zaciatok 63
end 3
zaciatok 63
end 3
zaciatok 62
end 2
zaciatok 62
end 2
zaciatok 62
end 2
zaciatok 62
end 2
zaciatok 62
end 2
zaciatok 62
end 2
zaciatok 62
end 2
zaciatok 62
end 2
zaciatok 62
end 2
zaciatok 62
end 2
zaciatok 62
end 2
zaciatok 62
end 2
zaciatok 62
end 2
zaciatok 62
end 2
zaciatok 62
end 2
zaciatok 62
end 2
zaciatok 62
end 2
zaciatok 61
end 1
zaciatok 61
end 1
zaciatok 61
end 1
zaciatok 61
end 1
zaciatok 61
end 1
zaciatok 61
end 1
zaciatok 61
end 1
zaciatok 61
end 1
zaciatok 61
end 1
zaciatok 61
end 1
zaciatok 61
end 1
zaciatok 61
end 1
zaciatok 61
end 1
zaciatok 61
end 1
zaciatok 61
end 1
zaciatok 61
end 1
zaciatok 61
end 1
zaciatok 61
end 1
zaciatok 61
end 1
zaciatok 61
end 1
zaciatok 60
end 0
zaciatok 60
end 0
zaciatok 60
end 0
zaciatok 60
end 0
zaciatok 60
end 0
zaciatok 60
end 0
zaciatok 60
end 0
zaciatok 60
end 0
zaciatok 60
end 0
zaciatok 60
end 0
zaciatok 60
end 0
zaciatok 60
end 0
zaciatok 60
end 0
zaciatok 60
end 0
zaciatok 59
end 4
zaciatok 59
end 4
zaciatok 59
end 4
zaciatok 59
end 4
zaciatok 59
end 4
zaciatok 59
end 4
zaciatok 59
end 4
zaciatok 59
end 4
zaciatok 59
end 4
zaciatok 59
end 4
zaciatok 59
end 4
zaciatok 59
end 4
zaciatok 59
end 4
zaciatok 59
end 4
zaciatok 59
end 4
zaciatok 59
end 4
zaciatok 59
end 4
zaciatok 59
end 4
zaciatok 59
end 4
zaciatok 59
end 4
zaciatok 58
end 3
zaciatok 58
end 3
zaciatok 58
end 3
zaciatok 58
end 3
zaciatok 58
end 3
zaciatok 58
end 3
zaciatok 58
end 3
zaciatok 58
end 3
zaciatok 58
end 3
zaciatok 58
end 3
zaciatok 58
end 3
zaciatok 58
end 3
zaciatok 58
end 3
zaciatok 57
end 2
zaciatok 57
end 2
zaciatok 57
end 2
zaciatok 57
end 2
zaciatok 57
end 2
zaciatok 57
end 2
zaciatok 57
end 2
zaciatok 57
end 2
zaciatok 57
end 2
zaciatok 57
end 2
zaciatok 57
end 2
zaciatok 57
end 2
zaciatok 57
end 2
zaciatok 57
end 2
zaciatok 57
end 2
zaciatok 57
end 2
zaciatok 57
end 2
zaciatok 57
end 2
zaciatok 57
end 2
zaciatok 57
end 2
zaciatok 57
end 2
zaciatok 57
end 2
zaciatok 56
end 1
zaciatok 56
end 1
zaciatok 56
end 1
zaciatok 56
end 1
zaciatok 56
end 1
zaciatok 56
end 1
zaciatok 56
end 1
zaciatok 56
end 1
zaciatok 56
end 1
zaciatok 56
end 1
zaciatok 56
end 1
zaciatok 56
end 1
zaciatok 56
end 1
zaciatok 56
end 1
zaciatok 56
end 1
zaciatok 56
end 1
zaciatok 56
end 1
zaciatok 56
end 1
zaciatok 55
end 0
zaciatok 55
end 0
zaciatok 55
end 0
zaciatok 55
end 0
zaciatok 55
end 0
zaciatok 55
end 0
zaciatok 55
end 0
zaciatok 55
end 0
zaciatok 55
end 0
zaciatok 55
end 0
zaciatok 55
end 0
zaciatok 55
end 0
zaciatok 55
end 0
zaciatok 54
end 4
zaciatok 54
end 4
zaciatok 54
end 4
zaciatok 54
end 4
zaciatok 54
end 4
zaciatok 54
end 4
zaciatok 54
end 4
zaciatok 54
end 4
zaciatok 54
end 4
zaciatok 54
end 4
zaciatok 54
end 4
zaciatok 54
end 4
zaciatok 54
end 4
zaciatok 54
end 4
zaciatok 54
end 4
zaciatok 54
end 4
zaciatok 54
end 4
zaciatok 54
end 4
zaciatok 54
end 4
zaciatok 54
end 4
zaciatok 54
end 4
zaciatok 54
end 4
zaciatok 54
end 4
zaciatok 54
end 4
zaciatok 53
end 3
zaciatok 53
end 3
zaciatok 53
end 3
zaciatok 53
end 3
zaciatok 53
end 3
zaciatok 53
end 3
zaciatok 53
end 3
zaciatok 53
end 3
zaciatok 53
end 3
zaciatok 53
end 3
zaciatok 53
end 3
zaciatok 53
end 3
zaciatok 53
end 3
zaciatok 53
end 3
zaciatok 53
end 3
zaciatok 53
end 3
zaciatok 53
end 3
zaciatok 53
end 3
zaciatok 53
end 3
zaciatok 53
end 3
zaciatok 53
end 3
zaciatok 53
end 3
zaciatok 53
end 3
zaciatok 53
end 3
zaciatok 53
end 3
zaciatok 53
end 3
zaciatok 53
end 3
zaciatok 53
end 3
zaciatok 53
end 3
zaciatok 53
end 3
zaciatok 52
end 2
zaciatok 52
end 2
zaciatok 52
end 2
zaciatok 52
end 2
zaciatok 52
end 2
zaciatok 52
end 2
zaciatok 52
end 2
zaciatok 52
end 2
zaciatok 52
end 2
zaciatok 52
end 2
zaciatok 52
end 2
zaciatok 52
end 2
zaciatok 52
end 2
zaciatok 52
end 2
zaciatok 52
end 2
zaciatok 52
end 2
zaciatok 52
end 2
zaciatok 52
end 2
zaciatok 52
end 2
zaciatok 52
end 2
zaciatok 52
end 2
zaciatok 52
end 2
zaciatok 52
end 2
zaciatok 52
end 2
zaciatok 52
end 2
zaciatok 52
end 2
zaciatok 51
end 1
zaciatok 51
end 1
zaciatok 51
end 1
zaciatok 51
end 1
zaciatok 51
end 1
zaciatok 51
end 1
zaciatok 51
end 1
zaciatok 51
end 1
zaciatok 51
end 1
zaciatok 51
end 1
zaciatok 51
end 1
zaciatok 51
end 1
zaciatok 51
end 1
zaciatok 51
end 1
zaciatok 51
end 1
zaciatok 51
end 1
zaciatok 51
end 1
zaciatok 51
end 1
zaciatok 51
end 1
zaciatok 51
end 1
zaciatok 51
end 1
zaciatok 50
end 0
zaciatok 50
end 0
zaciatok 50
end 0
zaciatok 50
end 0
zaciatok 50
end 0
zaciatok 50
end 0
zaciatok 50
end 0
zaciatok 50
end 0
zaciatok 50
end 0
zaciatok 50
end 0
zaciatok 50
end 0
zaciatok 50
end 0
zaciatok 50
end 0
zaciatok 50
end 0
zaciatok 50
end 0
zaciatok 50
end 0
zaciatok 50
end 0
zaciatok 50
end 0
zaciatok 50
end 0
zaciatok 50
end 0
zaciatok 50
end 0
zaciatok 50
end 0
zaciatok 50
end 0
zaciatok 50
end 0
zaciatok 50
end 0
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 49
end 4
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 48
end 3
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 47
end 2
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 46
end 1
zaciatok 45
end 0
zaciatok 45
end 0
zaciatok 45
end 0
zaciatok 45
end 0
zaciatok 45
end 0
zaciatok 45
end 0
zaciatok 45
end 0
zaciatok 45
end 0
zaciatok 45
end 0
zaciatok 45
end 0
zaciatok 45
end 0
zaciatok 45
end 0
zaciatok 45
end 0
zaciatok 45
end 0
zaciatok 45
end 0
zaciatok 45
end 0
zaciatok 45
end 0
zaciatok 45
end 0
zaciatok 45
end 0
zaciatok 45
end 0
zaciatok 45
end 0
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 44
end 4
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 43
end 3
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 42
end 2
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 41
end 1
zaciatok 40
end 0
zaciatok 40
end 0

In [53]:
user_sequences

[                     review_id                 user_id  \
 488637  ih0EwuprB0xNJLF3bugq4g  vFd8aBLg1kFcd0kCkoi-xw
 329984  T5Su0cLipsEmqA0aq6BAVw  vFd8aBLg1kFcd0kCkoi-xw
 445552  HPGzJv1vZIpUjgfT7FtygQ  vFd8aBLg1kFcd0kCkoi-xw
 203384  8BdCkdxsTdZV07kh8oovQg  vFd8aBLg1kFcd0kCkoi-xw
 368911  P1Ky8dZB5ECiCRFcJZqSfA  vFd8aBLg1kFcd0kCkoi-xw

                    business_id  stars_business  review_count_review  \
 488637  -1B9pP_CrRBJYPICE5WbRA           0.750             0.142932
 329984  laXWQMgAW2kUfAH7Y-xH8w           0.875             0.020119
 445552  atZ_olNKXOG4rEr6mccN8g           0.875             0.238453
 203384  oziGQYLaEWOpNmPKrZP86g           0.875             0.081700
 368911  t6g6Lj8WzjIXXucCl9jdTQ           0.750             0.069279

         Fuzhou_category  Themed Cafes_category  Burmese_category  \
 488637              0.0                    0.0               0.0
 329984              0.0                    0.0               0.0
 445552              0.0                    0.0               0.0
 203384              0.0                    0.0               0.0
 368911              0.0                    0.0               0.0

         Falafel_category  Cafes_category  ...  compliment_profile  \
 488637               0.0             0.0  ...            0.000142
 329984               0.0             0.0  ...            0.000142
 445552               0.0             0.0  ...            0.000142
 203384               0.0             0.0  ...            0.000142
 368911               0.0             0.0  ...            0.000142

         compliment_cute  compliment_list  compliment_note  compliment_plain  \
 488637              0.0              0.0         0.001152           0.00088
 329984              0.0              0.0         0.001152           0.00088
 445552              0.0              0.0         0.001152           0.00088
 203384              0.0              0.0         0.001152           0.00088
 368911              0.0              0.0         0.001152           0.00088

         compliment_cool  compliment_funny  compliment_writer  \
 488637         0.000861          0.000861            0.00182
 329984         0.000861          0.000861            0.00182
 445552         0.000861          0.000861            0.00182
 203384         0.000861          0.000861            0.00182
 368911         0.000861          0.000861            0.00182

         compliment_photos  number_of_friends
 488637           0.000838           0.009804
 329984           0.000838           0.009804
 445552           0.000838           0.009804
 203384           0.000838           0.009804
 368911           0.000838           0.009804

 [5 rows x 388 columns],
                      review_id                 user_id  \
 97353   EcUdFZsuiV95G8vQqK16hQ  vFd8aBLg1kFcd0kCkoi-xw
 374385  mnZKpMflTFOUFTPCifhKAg  vFd8aBLg1kFcd0kCkoi-xw
 450102  L5Bd6o37vtAQxS5Wnx75Gg  vFd8aBLg1kFcd0kCkoi-xw
 210860  2mV5lA67n5RiIdB-AY0u2g  vFd8aBLg1kFcd0kCkoi-xw
 181672  jDTg40FOmuNEEnVszguhbg  vFd8aBLg1kFcd0kCkoi-xw

                    business_id  stars_business  review_count_review  \
 97353   POuaebsAeCyNx-8qZ3O7XQ           0.750             0.057208
 374385  WC7xFGH4hV7ImLI7I0V9mw           0.750             0.002974
 450102  vuE1iseFrgNPumUEfHIZZQ           0.875             0.064906
 210860  hQY2yKi9OUGLgVApsK4h1Q           0.750             0.013471
 181672  M6ap9LXMEZmHf6NhlNpDQA           0.875             0.026592

         Fuzhou_category  Themed Cafes_category  Burmese_category  \
 97353               0.0                    0.0               0.0
 374385              0.0                    0.0               0.0
 450102              0.0                    0.0               0.0
 210860              0.0                    0.0               0.0
 181672              0.0                    0.0               0.0

         Falafel_category  Cafes_category  ...  compliment_profile  \
 97353                0.0             0.0  ...            0.000142
 374385               0.0             0.0  ...            0.000142
 450102               0.0             0.0  ...            0.000142
 210860               0.0             0.0  ...            0.000142
 181672               0.0             0.0  ...            0.000142

         compliment_cute  compliment_list  compliment_note  compliment_plain  \
 97353               0.0              0.0         0.001152           0.00088
 374385              0.0              0.0         0.001152           0.00088
 450102              0.0              0.0         0.001152           0.00088
 210860              0.0              0.0         0.001152           0.00088
 181672              0.0              0.0         0.001152           0.00088

         compliment_cool  compliment_funny  compliment_writer  \
 97353          0.000861          0.000861            0.00182
 374385         0.000861          0.000861            0.00182
 450102         0.000861          0.000861            0.00182
 210860         0.000861          0.000861            0.00182
 181672         0.000861          0.000861            0.00182

         compliment_photos  number_of_friends
 97353            0.000838           0.009804
 374385           0.000838           0.009804
 450102           0.000838           0.009804
 210860           0.000838           0.009804
 181672           0.000838           0.009804

 [5 rows x 388 columns],
                      review_id                 user_id  \
 181504  PgfxlvXzz0qB42Fr4tSQhQ  vFd8aBLg1kFcd0kCkoi-xw
 61301   5alMCSyfrVdPiZxaSq4CMA  vFd8aBLg1kFcd0kCkoi-xw
 267838  vK_aca3hPQYKXVkc11hhYw  vFd8aBLg1kFcd0kCkoi-xw
 74947   jHapjhfhjeCqF1R5GhIPOQ  vFd8aBLg1kFcd0kCkoi-xw
 186648  qF02xhYbAdmyxAd6qHY-JQ  vFd8aBLg1kFcd0kCkoi-xw

                    business_id  stars_business  review_count_review  \
 181504  uIFRFef7l43YxA8G3dU6Tg           0.875             0.020994
 61301   ZYRul0i1bhOjirHED6Kd0w           0.875             0.026767
 267838  VP8HMhVt-pKmqGNmDW4-TQ           0.750             0.071554
 74947   j-qtdD55OLfSqfsWuQTDJg           0.750             0.482155
 186648  erz6oUEJdx787WyOlxMARw           0.750             0.071728

         Fuzhou_category  Themed Cafes_category  Burmese_category  \
 181504              0.0                    0.0               0.0
 61301               0.0                    0.0               0.0
 267838              0.0                    0.0               0.0
 74947               0.0                    0.0               0.0
 186648              0.0                    0.0               0.0

         Falafel_category  Cafes_category  ...  compliment_profile  \
 181504               0.0             0.0  ...            0.000142
 61301                0.0             0.0  ...            0.000142
 267838               0.0             0.0  ...            0.000142
 74947                0.0             1.0  ...            0.000142
 186648               0.0             0.0  ...            0.000142

         compliment_cute  compliment_list  compliment_note  compliment_plain  \
 181504              0.0              0.0         0.001152           0.00088
 61301               0.0              0.0         0.001152           0.00088
 267838              0.0              0.0         0.001152           0.00088
 74947               0.0              0.0         0.001152           0.00088
 186648              0.0              0.0         0.001152           0.00088

         compliment_cool  compliment_funny  compliment_writer  \
 181504         0.000861          0.000861            0.00182
 61301          0.000861          0.000861            0.00182
 267838         0.000861          0.000861            0.00182
 74947          0.000861          0.000861            0.00182
 186648         0.000861          0.000861            0.00182

         compliment_photos  number_of_friends
 181504           0.000838           0.009804
 61301            0.000838           0.009804
 267838           0.000838           0.009804
 74947            0.000838           0.009804
 186648           0.000838           0.009804

 [5 rows x 388 columns],
                      review_id                 user_id  \
 169196  5iLLOlqFdWjVncTb121gQQ  vFd8aBLg1kFcd0kCkoi-xw
 28300   uc5loW2OnhlV6t2vYsKsYg  vFd8aBLg1kFcd0kCkoi-xw
 257755  LHlq9Unt1_FlCvos30VuTQ  vFd8aBLg1kFcd0kCkoi-xw
 346729  5YmhSJaek9HjskSfyHI7gQ  vFd8aBLg1kFcd0kCkoi-xw
 112439  xCCFALcVCrVNAJb3QNsRPA  vFd8aBLg1kFcd0kCkoi-xw

                    business_id  stars_business  review_count_review  \
 169196  V8we7-uCa-SouadZmZ9Ieg           0.500             0.065780
 28300   eaDZlSuVS0EY67Ke6pRP6Q           0.625             0.193667
 257755  qY-BUQY-SFBaSrFHowF3nA           0.750             0.211337
 346729  zujdPV3HT-Y-CKE1GgkMHQ           0.875             0.059657
 112439  RBCtHLVvc230q8zkRWIoyQ           0.875             0.027992

         Fuzhou_category  Themed Cafes_category  Burmese_category  \
 169196              0.0                    0.0               0.0
 28300               0.0                    0.0               0.0
 257755              0.0                    0.0               0.0
 346729              0.0                    0.0               0.0
 112439              0.0                    0.0               0.0

         Falafel_category  Cafes_category  ...  compliment_profile  \
 169196               0.0             0.0  ...            0.000142
 28300                0.0             0.0  ...            0.000142
 257755               0.0             0.0  ...            0.000142
 346729               0.0             0.0  ...            0.000142
 112439               0.0             1.0  ...            0.000142

         compliment_cute  compliment_list  compliment_note  compliment_plain  \
 169196              0.0              0.0         0.001152           0.00088
 28300               0.0              0.0         0.001152           0.00088
 257755              0.0              0.0         0.001152           0.00088
 346729              0.0              0.0         0.001152           0.00088
 112439              0.0              0.0         0.001152           0.00088

         compliment_cool  compliment_funny  compliment_writer  \
 169196         0.000861          0.000861            0.00182
 28300          0.000861          0.000861            0.00182
 257755         0.000861          0.000861            0.00182
 346729         0.000861          0.000861            0.00182
 112439         0.000861          0.000861            0.00182

         compliment_photos  number_of_friends
 169196           0.000838           0.009804
 28300            0.000838           0.009804
 257755           0.000838           0.009804
 346729           0.000838           0.009804
 112439           0.000838           0.009804

 [5 rows x 388 columns],
                      review_id                 user_id  \
 228143  tFGVLgUPFBWKPZve6AW8Aw  vFd8aBLg1kFcd0kCkoi-xw
 73147   oRhJn9IPESstmbxvtX77xQ  vFd8aBLg1kFcd0kCkoi-xw
 314010  O77mQL0lUfX3wJ0A69g4QA  vFd8aBLg1kFcd0kCkoi-xw
 151147  KWbtrXk7LOUD-ljGloPDGw  vFd8aBLg1kFcd0kCkoi-xw
 342043  Bei9prOeoRA7uv4Mg-1MCA  vFd8aBLg1kFcd0kCkoi-xw

                    business_id  stars_business  review_count_review  \
 228143  _Q3XmBesceFqn9Dk-w6tlA           0.875             0.033065
 73147   bwgK5d9oT2sUcvyBOsTREQ           0.875             0.038314
 314010  Jg9kkOl4sx2AXJVohbpSiw           0.875             0.102869
 151147  dtsnh96yn64IT7sErc509g           0.625             0.008747
 342043  r3X75SK37buS94mDls3q_Q           0.875             0.047936

         Fuzhou_category  Themed Cafes_category  Burmese_category  \
 228143              0.0                    0.0               0.0
 73147               0.0                    0.0               0.0
 314010              0.0                    0.0               0.0
 151147              0.0                    0.0               0.0
 342043              0.0                    0.0               0.0

         Falafel_category  Cafes_category  ...  compliment_profile  \
 228143               0.0             0.0  ...            0.000142
 73147                0.0             0.0  ...            0.000142
 314010               0.0             0.0  ...            0.000142
 151147               0.0             0.0  ...            0.000142
 342043               0.0             0.0  ...            0.000142

         compliment_cute  compliment_list  compliment_note  compliment_plain  \
 228143              0.0              0.0         0.001152           0.00088
 73147               0.0              0.0         0.001152           0.00088
 314010              0.0              0.0         0.001152           0.00088
 151147              0.0              0.0         0.001152           0.00088
 342043              0.0              0.0         0.001152           0.00088

         compliment_cool  compliment_funny  compliment_writer  \
 228143         0.000861          0.000861            0.00182
 73147          0.000861          0.000861            0.00182
 314010         0.000861          0.000861            0.00182
 151147         0.000861          0.000861            0.00182
 342043         0.000861          0.000861            0.00182

         compliment_photos  number_of_friends
 228143           0.000838           0.009804
 73147            0.000838           0.009804
 314010           0.000838           0.009804
 151147           0.000838           0.009804
 342043           0.000838           0.009804

 [5 rows x 388 columns],
                      review_id                 user_id  \
 25068   n1AXP2_Ry0OWMpLKAp0aCw  vFd8aBLg1kFcd0kCkoi-xw
 396574  LL6VP6qfn06RUavAiigEDQ  vFd8aBLg1kFcd0kCkoi-xw
 28365   nKLRz2wMfWtUrLbCuKGZ-A  vFd8aBLg1kFcd0kCkoi-xw
 310709  1DxXDhWVjswWE22a5qzkHA  vFd8aBLg1kFcd0kCkoi-xw
 79321   m6ylTNpYMlP0OJWiMZxi7Q  vFd8aBLg1kFcd0kCkoi-xw

                    business_id  stars_business  review_count_review  \
 25068   mbglgx3nbRRPKxh0SxDjNQ           0.875             0.034465
 396574  Cz-2ekKVyKheFccKtYP1YA           0.875             0.012421
 28365   eaDZlSuVS0EY67Ke6pRP6Q           0.625             0.193667
 310709  6_T2xzR74JqGCTPefAD8Tw           0.875             0.333975
 79321   Al8y5FTs9tW5VsxTVy9ZMg           0.750             0.049685

         Fuzhou_category  Themed Cafes_category  Burmese_category  \
 25068               0.0                    0.0               0.0
 396574              0.0                    0.0               0.0
 28365               0.0                    0.0               0.0
 310709              0.0                    0.0               0.0
 79321               0.0                    0.0               0.0

         Falafel_category  Cafes_category  ...  compliment_profile  \
 25068                0.0             0.0  ...            0.000142
 396574               0.0             0.0  ...            0.000142
 28365                0.0             0.0  ...            0.000142
 310709               0.0             0.0  ...            0.000142
 79321                0.0             0.0  ...            0.000142

         compliment_cute  compliment_list  compliment_note  compliment_plain  \
 25068               0.0              0.0         0.001152           0.00088
 396574              0.0              0.0         0.001152           0.00088
 28365               0.0              0.0         0.001152           0.00088
 310709              0.0              0.0         0.001152           0.00088
 79321               0.0              0.0         0.001152           0.00088

         compliment_cool  compliment_funny  compliment_writer  \
 25068          0.000861          0.000861            0.00182
 396574         0.000861          0.000861            0.00182
 28365          0.000861          0.000861            0.00182
 310709         0.000861          0.000861            0.00182
 79321          0.000861          0.000861            0.00182

         compliment_photos  number_of_friends
 25068            0.000838           0.009804
 396574           0.000838           0.009804
 28365            0.000838           0.009804
 310709           0.000838           0.009804
 79321            0.000838           0.009804

 [5 rows x 388 columns],
                      review_id                 user_id  \
 255952  LfGqG_PM92J56kULkyalIw  vFd8aBLg1kFcd0kCkoi-xw
 412800  35XEEudmkmfV15R29HVDUQ  vFd8aBLg1kFcd0kCkoi-xw
 158131  STAtijcX2KEMF7Vsxyu2Kw  vFd8aBLg1kFcd0kCkoi-xw
 221925  FlQBKlaMuBh3I4waqcSetg  vFd8aBLg1kFcd0kCkoi-xw
 238976  E20amNtWk-xRfg_6_Dq4rg  vFd8aBLg1kFcd0kCkoi-xw

                    business_id  stars_business  review_count_review  \
 255952  R17gwW6zn9ilslbdvKdgsg           0.750             0.230231
 412800  NWF16GKQyZNVHo086gIVzQ           0.625             0.031840
 158131  hljCyVrQuuYtMj2D1g5DDA           0.750             0.016970
 221925  Wtr51cNrv1pYyIRg_IawYQ           0.875             0.075577
 238976  0S3TvsmbCeOZ9UitnpRd1A           0.750             0.087474

         Fuzhou_category  Themed Cafes_category  Burmese_category  \
 255952              0.0                    0.0               0.0
 412800              0.0                    0.0               0.0
 158131              0.0                    0.0               0.0
 221925              0.0                    0.0               0.0
 238976              0.0                    0.0               0.0

         Falafel_category  Cafes_category  ...  compliment_profile  \
 255952               0.0             0.0  ...            0.000142
 412800               0.0             0.0  ...            0.000142
 158131               0.0             0.0  ...            0.000142
 221925               0.0             0.0  ...            0.000142
 238976               0.0             0.0  ...            0.000142

         compliment_cute  compliment_list  compliment_note  compliment_plain  \
 255952              0.0              0.0         0.001152           0.00088
 412800              0.0              0.0         0.001152           0.00088
 158131              0.0              0.0         0.001152           0.00088
 221925              0.0              0.0         0.001152           0.00088
 238976              0.0              0.0         0.001152           0.00088

         compliment_cool  compliment_funny  compliment_writer  \
 255952         0.000861          0.000861            0.00182
 412800         0.000861          0.000861            0.00182
 158131         0.000861          0.000861            0.00182
 221925         0.000861          0.000861            0.00182
 238976         0.000861          0.000861            0.00182

         compliment_photos  number_of_friends
 255952           0.000838           0.009804
 412800           0.000838           0.009804
 158131           0.000838           0.009804
 221925           0.000838           0.009804
 238976           0.000838           0.009804

 [5 rows x 388 columns],
                      review_id                 user_id  \
 323135  bj8k5Yxzw1Q0ME3ywOItXw  vFd8aBLg1kFcd0kCkoi-xw
 133040  LVGBqnPGHIUAI25tBGQy_g  vFd8aBLg1kFcd0kCkoi-xw
 361305  6yuKf7xDRnNhhFleZWqLYA  vFd8aBLg1kFcd0kCkoi-xw
 7181    w15qCB87H0m8vU6stFDzpQ  vFd8aBLg1kFcd0kCkoi-xw
 322808  TIIlDQPE-GokQbwBtkVfBA  vFd8aBLg1kFcd0kCkoi-xw

                    business_id  stars_business  review_count_review  \
 323135  xb5NsCqvQw2uE5HoQyDr0g           0.875             0.029041
 133040  vVfy055EfLMdd0yJYHxiMQ           0.875             0.120014
 361305  _V6hl1oGkTV2KbGeax_HPA           0.750             0.161127
 7181    eqNutOMnPqKa9QDAY6KfEw           0.875             0.053359
 322808  0-7N3z_cb3Z1xMGDrbez6w           0.750             0.067180

         Fuzhou_category  Themed Cafes_category  Burmese_category  \
 323135              0.0                    0.0               0.0
 133040              0.0                    0.0               0.0
 361305              0.0                    0.0               0.0

In [21]:
len(user_sequences)

49560

In [22]:
len(user_sequences_copy)

49560

In [ ]:
# merged

,review_id,user_id,business_id,stars_business,review_count_review,Fuzhou_category,Themed Cafes_category,Burmese_category,Falafel_category,Cafes_category,...,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos,number_of_friends
0,BXQcBN0iAi1lAUxibGLFzA,6_SpY41LIHZuIaiDs5FMKA,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000063,0.000000,0.000000
1,uduvUCvi9w3T2bSGivCfXg,tCXElwhzekJEH6QJe3xs7Q,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.000852,0.000336,0.000000,0.000186,0.000277,0.000921,0.000921,0.001632,0.000356,0.012338
2,a0vwPOqDXXZuJkbBW2356g,WqfKtI-aGMmvbA9pPUxNQQ,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000051,0.000079,0.000040,0.000040,0.000314,0.000000,0.001134
3,MKNp_CdR2k2202-c8GN5Dw,3-1va0IQfK-9tUMzfHWfTA,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000200
4,D1GisLDPe84Rrk_R4X2brQ,EouCKoDfzaVG0klEgdDvCQ,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000336,0.001534,0.000407,0.000504,0.000700,0.000700,0.000816,0.000089,0.009337
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511133,qBcwQEQPnLxjkw-xbUIF4Q,6nF5PT1c0dF6EpOgQdF2tw,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000010,0.000000,0.000000,0.000000,0.000000,0.000000
511134,G8fbysnUAUmqq1XWTjMQ4Q,1M78_w4J9f5S8xmUVYyxdQ,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000051,0.000030,0.000080,0.000080,0.000063,0.000053,0.000333
511135,JKiy0aeyGd3KmXN7uRPFLw,B7TD5yTemGv50y4wM2EVNA,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
511136,JITY01bGbdsiUBznLz9rdg,HI8QwhpeP_ZRY5JZy11VDw,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000085,0.000000,0.000000,0.000000,0.000000,0.000000,0.005069
511137,VzKF0662H2NLbpbmGv20Ug,CmR9s-2zH20UkmUt5Qwqnw,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000102,0.000020,0.000080,0.000080,0.000126,0.000000,0.005202

In [23]:
user_matrix = np.array(
    [user_df.drop(columns=["review_id", "user_id", "business_id"]).to_numpy() for user_df in user_sequences]
)

In [24]:
user_matrix_y = np.array(
    [user_df.drop(columns=["review_id", "user_id", "business_id"]).to_numpy() for user_df in user_sequences_copy]
)

In [26]:
display(user_matrix.shape)
display(user_matrix.dtype)

(49560, 5, 385)

dtype('float64')

In [27]:
display(user_matrix_y.shape)
display(user_matrix_y.dtype)

(49560, 5, 362)

dtype('float64')

In [ ]:
# user_matrix = np.array(
#     [merged[merged["user_id"] == user_id].sort_values("date").drop(labels=["review_id", "user_id", "business_id"], axis=1).to_numpy() for user_id in indexes]
# )

In [ ]:
# user_matrix_y = np.array(
#     [merged_copy[merged_copy["user_id"] == user_id].sort_values("date").drop(labels=["review_id", "user_id", "business_id", "date"], axis=1).to_numpy() for user_id in indexes]
# )

In [28]:
X_train, X_test, y_train, y_test = train_test_split(user_matrix, user_matrix_y, train_size=0.8, random_state=28)

In [29]:
display(X_train.shape)
display(X_train.dtype)
display(X_test.shape)
display(X_test.dtype)
display(y_train.shape)
display(y_train.dtype)
display(y_test.shape)
display(y_test.dtype)

(39648, 5, 385)

dtype('float64')

(9912, 5, 385)

dtype('float64')

(39648, 5, 362)

dtype('float64')

(9912, 5, 362)

dtype('float64')

In [ ]:
X_train = X_train[:, :sequence_length-1, :]
X_test = X_test[:, :sequence_length-1, :]
y_train = y_train[:, sequence_length-1:, :]
y_test = y_test[:, sequence_length-1:, :]

In [31]:
display(X_train.shape)
display(X_test.shape)
display(y_train.shape)
display(y_test.shape)

(39648, 4, 385)

(9912, 4, 385)

(39648, 1, 362)

(9912, 1, 362)

In [32]:
display(0.1/(32*4*385))
display(1/(32*4*385))
display((0.1/(32*4*385)) + (1/(32*4*385)))

2.0292207792207792e-06

2.0292207792207792e-05

2.232142857142857e-05

In [33]:
# hyperparameters and stuff
learning_rate = 0.000001
number_of_epochs = 300
batch_size = 32

In [34]:
class ModelCallback(keras.callbacks.Callback):
    def __init__(self, X_test, y_test, batch_size):
        self.X_test = X_test
        self.y_test = y_test
        self.batch_size = batch_size

    def on_epoch_end(self, epoch, logs=None):
        new_logs = dict()
        for metric in logs:
            new_logs["train_" + metric] = logs[metric]
        evaluation = self.model.evaluate(x=self.X_test, y=self.y_test, batch_size=self.batch_size)
        loss = evaluation[0]
        mae = evaluation[1]
        new_logs["test_loss"] = loss
        new_logs["test_mae"] = mae
        run.log(new_logs)

    def on_train_end(self, logs=None):
        pass

    def on_epoch_begin(self, epoch, logs=None):
        pass

    def on_test_begin(self, logs=None):
        pass

    def on_test_end(self, logs=None):
        pass

In [39]:
model = Sequential([
    LSTM(512, activation="tanh", return_sequences=True, input_shape=(sequence_length-1, 385)),
    LSTM(384, activation="tanh"),
    Dense(256, activation="relu"),
    # Dropout(0.1),
    Dense(362, activation="tanh"), # nejako to rozdelit na ratingy a binarne featury
])
optimizer = keras.optimizers.Adam()
optimizer.learning_rate.assign(learning_rate)
model.compile(optimizer=optimizer, loss='mse', metrics=['mae'])
model.summary()

/home/kristofs/School/ISA/ISA_project/.venv/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_2 (LSTM)                   │ (None, 4, 512)         │     1,839,104 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_3 (LSTM)                   │ (None, 384)            │     1,377,792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 256)            │        98,560 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 362)            │        93,034 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,408,490 (13.00 MB)

 Trainable params: 3,408,490 (13.00 MB)

 Non-trainable params: 0 (0.00 B)

In [40]:
model_callback = ModelCallback(
    X_test=X_test,
    y_test=y_test,
    batch_size=batch_size
)

In [37]:
run = wandb.init(
    entity="ISA2026",
    project="hello_world",
    name="test_run",
    config={
        "learning_rate": learning_rate,
        "number_of_epochs": number_of_epochs,
        "batch_size": batch_size,
    },
)
run.log_code(".", include_fn=lambda path: path.endswith(".ipynb"))

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/kristofs/.netrc.
wandb: Currently logged in as: stanislavkristof to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

In [41]:
history = model.fit(X_train, y_train, epochs=number_of_epochs, batch_size=batch_size, verbose=2, callbacks=[model_callback])

Epoch 1/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.1655 - mae: 0.2565
1239/1239 - 28s - 22ms/step - loss: 0.1916 - mae: 0.2435
Epoch 2/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.1191 - mae: 0.2380
1239/1239 - 26s - 21ms/step - loss: 0.1399 - mae: 0.2517
Epoch 3/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0950 - mae: 0.2022
1239/1239 - 26s - 21ms/step - loss: 0.1060 - mae: 0.2200
Epoch 4/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0823 - mae: 0.1758
1239/1239 - 25s - 20ms/step - loss: 0.0881 - mae: 0.1883
Epoch 5/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0774 - mae: 0.1608
1239/1239 - 25s - 20ms/step - loss: 0.0796 - mae: 0.1674
Epoch 6/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0760 - mae: 0.1559
1239/1239 - 25s - 20ms/step - loss: 0.0768 - mae: 0.1579
Epoch 7/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0754 - mae: 0.1544
1239/1239 - 25s - 20ms/step - loss: 0.0759 - mae: 0.1551
Epoch 8/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0752 - mae: 0.1535
1239/1239 - 25s - 20ms/step - loss: 0.0755 - mae: 0.1540
Epoch 9/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0751 - mae: 0.1529
1239/1239 - 25s - 20ms/step - loss: 0.0753 - mae: 0.1533
Epoch 10/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0750 - mae: 0.1526
1239/1239 - 25s - 20ms/step - loss: 0.0752 - mae: 0.1528
Epoch 11/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0750 - mae: 0.1524
1239/1239 - 25s - 20ms/step - loss: 0.0752 - mae: 0.1525
Epoch 12/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0750 - mae: 0.1522
1239/1239 - 24s - 20ms/step - loss: 0.0752 - mae: 0.1523
Epoch 13/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0750 - mae: 0.1520
1239/1239 - 24s - 20ms/step - loss: 0.0752 - mae: 0.1522
Epoch 14/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0750 - mae: 0.1519
1239/1239 - 25s - 20ms/step - loss: 0.0752 - mae: 0.1520
Epoch 15/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0750 - mae: 0.1518
1239/1239 - 25s - 20ms/step - loss: 0.0752 - mae: 0.1519
Epoch 16/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0750 - mae: 0.1517
1239/1239 - 25s - 20ms/step - loss: 0.0752 - mae: 0.1518
Epoch 17/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0750 - mae: 0.1517
1239/1239 - 25s - 20ms/step - loss: 0.0752 - mae: 0.1518
Epoch 18/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0750 - mae: 0.1516
1239/1239 - 25s - 20ms/step - loss: 0.0752 - mae: 0.1517
Epoch 19/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0750 - mae: 0.1516
1239/1239 - 26s - 21ms/step - loss: 0.0752 - mae: 0.1517
Epoch 20/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0750 - mae: 0.1515
1239/1239 - 26s - 21ms/step - loss: 0.0752 - mae: 0.1516
Epoch 21/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0750 - mae: 0.1515
1239/1239 - 26s - 21ms/step - loss: 0.0752 - mae: 0.1516
Epoch 22/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0750 - mae: 0.1515
1239/1239 - 26s - 21ms/step - loss: 0.0752 - mae: 0.1516
Epoch 23/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0750 - mae: 0.1515
1239/1239 - 26s - 21ms/step - loss: 0.0752 - mae: 0.1515
Epoch 24/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0750 - mae: 0.1514
1239/1239 - 26s - 21ms/step - loss: 0.0752 - mae: 0.1515
Epoch 25/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0750 - mae: 0.1514
1239/1239 - 26s - 21ms/step - loss: 0.0752 - mae: 0.1515
Epoch 26/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0750 - mae: 0.1514
1239/1239 - 26s - 21ms/step - loss: 0.0752 - mae: 0.1515
Epoch 27/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0750 - mae: 0.1514
1239/1239 - 26s - 21ms/step - loss: 0.0752 - mae: 0.1515
Epoch 28/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0750 - mae: 0.1514
1239/1239 - 26s - 21ms/step - loss: 0.0752 - mae: 0.1514
Epoch 29/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0750 - mae: 0.1514
1239/1239 - 26s - 21ms/step - loss: 0.0752 - mae: 0.1514
Epoch 30/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0750 - mae: 0.1514
1239/1239 - 26s - 21ms/step - loss: 0.0752 - mae: 0.1514
Epoch 31/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0750 - mae: 0.1513
1239/1239 - 26s - 21ms/step - loss: 0.0752 - mae: 0.1514
Epoch 32/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1513
1239/1239 - 27s - 22ms/step - loss: 0.0752 - mae: 0.1514
Epoch 33/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1513
1239/1239 - 26s - 21ms/step - loss: 0.0752 - mae: 0.1514
Epoch 34/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1513
1239/1239 - 26s - 21ms/step - loss: 0.0752 - mae: 0.1514
Epoch 35/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1513
1239/1239 - 26s - 21ms/step - loss: 0.0752 - mae: 0.1514
Epoch 36/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1513
1239/1239 - 25s - 20ms/step - loss: 0.0752 - mae: 0.1514
Epoch 37/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0749 - mae: 0.1513
1239/1239 - 28s - 22ms/step - loss: 0.0752 - mae: 0.1514
Epoch 38/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1513
1239/1239 - 26s - 21ms/step - loss: 0.0752 - mae: 0.1514
Epoch 39/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1513
1239/1239 - 24s - 20ms/step - loss: 0.0752 - mae: 0.1513
Epoch 40/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1513
1239/1239 - 24s - 20ms/step - loss: 0.0752 - mae: 0.1513
Epoch 41/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1513
1239/1239 - 24s - 20ms/step - loss: 0.0752 - mae: 0.1513
Epoch 42/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1513
1239/1239 - 24s - 20ms/step - loss: 0.0752 - mae: 0.1513
Epoch 43/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1513
1239/1239 - 24s - 20ms/step - loss: 0.0752 - mae: 0.1513
Epoch 44/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1513
1239/1239 - 24s - 20ms/step - loss: 0.0752 - mae: 0.1513
Epoch 45/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1512
1239/1239 - 24s - 20ms/step - loss: 0.0752 - mae: 0.1513
Epoch 46/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1512
1239/1239 - 24s - 20ms/step - loss: 0.0752 - mae: 0.1513
Epoch 47/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1512
1239/1239 - 24s - 20ms/step - loss: 0.0751 - mae: 0.1513
Epoch 48/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1512
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1513
Epoch 49/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1512
1239/1239 - 26s - 21ms/step - loss: 0.0751 - mae: 0.1513
Epoch 50/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1512
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1513
Epoch 51/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1512
1239/1239 - 26s - 21ms/step - loss: 0.0751 - mae: 0.1513
Epoch 52/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1512
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1513
Epoch 53/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1512
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1513
Epoch 54/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1512
1239/1239 - 24s - 20ms/step - loss: 0.0751 - mae: 0.1513
Epoch 55/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1512
1239/1239 - 24s - 20ms/step - loss: 0.0751 - mae: 0.1513
Epoch 56/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1512
1239/1239 - 24s - 20ms/step - loss: 0.0751 - mae: 0.1513
Epoch 57/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1512
1239/1239 - 24s - 20ms/step - loss: 0.0751 - mae: 0.1513
Epoch 58/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1512
1239/1239 - 24s - 20ms/step - loss: 0.0751 - mae: 0.1513
Epoch 59/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1512
1239/1239 - 24s - 20ms/step - loss: 0.0751 - mae: 0.1513
Epoch 60/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1512
1239/1239 - 24s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 61/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1512
1239/1239 - 24s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 62/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1512
1239/1239 - 27s - 22ms/step - loss: 0.0751 - mae: 0.1512
Epoch 63/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1512
1239/1239 - 27s - 22ms/step - loss: 0.0751 - mae: 0.1512
Epoch 64/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0749 - mae: 0.1512
1239/1239 - 26s - 21ms/step - loss: 0.0751 - mae: 0.1512
Epoch 65/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1512
1239/1239 - 27s - 22ms/step - loss: 0.0751 - mae: 0.1512
Epoch 66/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1512
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 67/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1512
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 68/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1512
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 69/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1512
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 70/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1512
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 71/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1512
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 72/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1512
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 73/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 74/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 75/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 26s - 21ms/step - loss: 0.0751 - mae: 0.1512
Epoch 76/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 77/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 78/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 79/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 80/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 81/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 82/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 83/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 84/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 85/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 86/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 87/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 24s - 19ms/step - loss: 0.0751 - mae: 0.1512
Epoch 88/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 26s - 21ms/step - loss: 0.0751 - mae: 0.1512
Epoch 89/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 90/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 26s - 21ms/step - loss: 0.0751 - mae: 0.1512
Epoch 91/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 26s - 21ms/step - loss: 0.0751 - mae: 0.1512
Epoch 92/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 26s - 21ms/step - loss: 0.0751 - mae: 0.1512
Epoch 93/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 26s - 21ms/step - loss: 0.0751 - mae: 0.1512
Epoch 94/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 26s - 21ms/step - loss: 0.0751 - mae: 0.1512
Epoch 95/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 26s - 21ms/step - loss: 0.0751 - mae: 0.1512
Epoch 96/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 26s - 21ms/step - loss: 0.0751 - mae: 0.1512
Epoch 97/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 26s - 21ms/step - loss: 0.0751 - mae: 0.1512
Epoch 98/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 26s - 21ms/step - loss: 0.0751 - mae: 0.1512
Epoch 99/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 26s - 21ms/step - loss: 0.0751 - mae: 0.1512
Epoch 100/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 26s - 21ms/step - loss: 0.0751 - mae: 0.1512
Epoch 101/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 27s - 22ms/step - loss: 0.0751 - mae: 0.1512
Epoch 102/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 26s - 21ms/step - loss: 0.0751 - mae: 0.1512
Epoch 103/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 104/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 105/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 106/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 107/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 108/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 109/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1512
Epoch 110/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1511
Epoch 111/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1511
Epoch 112/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1511
Epoch 113/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 26s - 21ms/step - loss: 0.0751 - mae: 0.1511
Epoch 114/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 24s - 20ms/step - loss: 0.0751 - mae: 0.1511
Epoch 115/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1511
Epoch 116/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 24s - 20ms/step - loss: 0.0751 - mae: 0.1511
Epoch 117/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 24s - 20ms/step - loss: 0.0751 - mae: 0.1511
Epoch 118/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1511
Epoch 119/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1511
Epoch 120/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 24s - 20ms/step - loss: 0.0751 - mae: 0.1511
Epoch 121/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 24s - 19ms/step - loss: 0.0751 - mae: 0.1511
Epoch 122/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 24s - 19ms/step - loss: 0.0751 - mae: 0.1511
Epoch 123/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 24s - 19ms/step - loss: 0.0751 - mae: 0.1511
Epoch 124/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 24s - 19ms/step - loss: 0.0751 - mae: 0.1511
Epoch 125/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 24s - 19ms/step - loss: 0.0751 - mae: 0.1511
Epoch 126/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1511
Epoch 127/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 26s - 21ms/step - loss: 0.0751 - mae: 0.1511
Epoch 128/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1511
Epoch 129/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1511
Epoch 130/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1511
Epoch 131/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1511
Epoch 132/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1511
Epoch 133/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1511
Epoch 134/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1511
Epoch 135/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1511
Epoch 136/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 21ms/step - loss: 0.0751 - mae: 0.1511
Epoch 137/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 26s - 21ms/step - loss: 0.0751 - mae: 0.1511
Epoch 138/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 26s - 21ms/step - loss: 0.0751 - mae: 0.1511
Epoch 139/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1511
Epoch 140/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1511
Epoch 141/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1511
Epoch 142/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511
1239/1239 - 25s - 20ms/step - loss: 0.0751 - mae: 0.1511
Epoch 143/300
310/310 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0749 - mae: 0.1511

In [ ]:
model.evaluate(x=X_test, y=y_test, batch_size=batch_size, verbose=2)

In [39]:
run.finish()