In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.models import Sequential
import keras
keras.utils.set_random_seed(28)
import datetime
from icecream import ic
from itertools import product
from sklearn.preprocessing import MinMaxScaler

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1776268373.210709   16412 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1776268373.212163   16412 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1776268373.298585   16412 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1776268375.907623   16412 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1776268375.908368   16412 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

In [2]:
CUSTOM_DATASET_PATH = Path("custom_data/")

In [3]:
merged = pd.read_csv(CUSTOM_DATASET_PATH / "merged.csv")
merged

,business_id,latitude,longitude,stars_business,review_count_review,Fuzhou_category,Themed Cafes_category,Burmese_category,Falafel_category,Cafes_category,...,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos,number_of_friends
0,MTSW4McQd7CbVtyjqoe9mw,39.955505,-75.155564,4.0,80,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
1,MTSW4McQd7CbVtyjqoe9mw,39.955505,-75.155564,4.0,80,0,0,0,0,0,...,6,1,0,11,28,46,46,26,20,186
2,MTSW4McQd7CbVtyjqoe9mw,39.955505,-75.155564,4.0,80,0,0,0,0,0,...,0,0,0,3,8,2,2,5,0,18
3,MTSW4McQd7CbVtyjqoe9mw,39.955505,-75.155564,4.0,80,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
4,MTSW4McQd7CbVtyjqoe9mw,39.955505,-75.155564,4.0,80,0,0,0,0,0,...,0,1,4,24,51,35,35,13,5,141
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511133,WnT9NIzQgLlILjPT0kEcsQ,39.935982,-75.158665,4.5,35,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
511134,WnT9NIzQgLlILjPT0kEcsQ,39.935982,-75.158665,4.5,35,0,0,0,0,0,...,0,0,0,3,3,4,4,1,3,6
511135,WnT9NIzQgLlILjPT0kEcsQ,39.935982,-75.158665,4.5,35,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
511136,WnT9NIzQgLlILjPT0kEcsQ,39.935982,-75.158665,4.5,35,0,0,0,0,0,...,0,0,0,5,0,0,0,0,0,77
511137,WnT9NIzQgLlILjPT0kEcsQ,39.935982,-75.158665,4.5,35,0,0,0,0,0,...,0,0,0,6,2,4,4,2,0,79

In [4]:
weekdays = ("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")
merged = merged.drop(columns=[weekday.lower() + suffix for weekday, suffix in product(weekdays, ("_opening", "_closing", "_opening_length_hours"))])

In [5]:
merged = merged.drop(columns=["latitude", "longitude"])

In [6]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    display(merged.isnull().sum())

business_id                                         0
stars_business                                      0
review_count_review                                 0
Fuzhou_category                                     0
Themed Cafes_category                               0
Burmese_category                                    0
Falafel_category                                    0
Cafes_category                                      0
Conveyor Belt Sushi_category                        0
Australian_category                                 0
Sushi Bars_category                                 0
Mongolian_category                                  0
New Mexican Cuisine_category                        0
Poutineries_category                                0
Ethiopian_category                                  0
Hong Kong Style Cafe_category                       0
Cafeteria_category                                  0
Chicken Shop_category                               0
Vegetarian_category                                 0
Asian Fusion_category                               0
Pan Asian_category                                  0
Dinner Theater_category                             0
Hawaiian_category                                   0
Fish & Chips_category                               0
French_category                                     0
Filipino_category                                   0
Seafood_category                                    0
Szechuan_category                                   0
Modern European_category                            0
Himalayan/Nepalese_category                         0
Senegalese_category                                 0
Portuguese_category                                 0
Delis_category                                      0
Vegan_category                                      0
Spanish_category                                    0
Uzbek_category                                      0
Iberian_category                                    0
Steakhouses_category                                0
Italian_category                                    0
Trinidadian_category                                0
Lebanese_category                                   0
Wraps_category                                      0
Bangladeshi_category                                0
Diners_category                                     0
Tapas Bars_category                                 0
Israeli_category                                    0
Pizza_category                                      0
Hainan_category                                     0
Korean_category                                     0
Tapas/Small Plates_category                         0
Russian_category                                    0
Afghan_category                                     0
Mexican_category                                    0
Live/Raw Food_category                              0
Greek_category                                      0
Teppanyaki_category                                 0
Polish_category                                     0
Hot Pot_category                                    0
Hot Dogs_category                                   0
Hungarian_category                                  0
Indian_category                                     0
Food Stands_category                                0
German_category                                     0
Southern_category                                   0
Indonesian_category                                 0
African_category                                    0
Sardinian_category                                  0
Buffets_category                                    0
Cambodian_category                                  0
Waffles_category                                    0
Sandwiches_category                                 0
Chinese_category                                    0
Dominican_category                                  0
Barbeque_category                                   0
Salad_category                                      0
Ukrainian_category                                  0
Vietnamese_category                                 0
Soul Food_category                                  0
Supper Clubs_category                               0
Gluten-Free_category                                0
Soup_category                                       0
Gastropubs_category                                 0
Tex-Mex_category                                    0
Kebab_category                                      0
Tacos_category                                      0
Scandinavian_category                               0
Food Court_category                                 0
Irish_category                                      0
Cajun/Creole_category                               0
Armenian_category                                   0
Laotian_category                                    0
Comfort Food_category                               0
Cantonese_category                                  0
Brasseries_category                                 0
Kosher_category                                     0
Haitian_category                                    0
Dim Sum_category                                    0
Cuban_category                                      0
Chicken Wings_category                              0
Colombian_category                                  0
Peruvian_category                                   0
Basque_category                                     0
Mediterranean_category                              0
Honduran_category                                   0
Ramen_category                                      0
Pop-Up Restaurants_category                         0
Fast Food_category                                  0
Latin American_category                             0
Persian/Iranian_category                            0
Puerto Rican_category                               0
Brazilian_category                                  0
Argentine_category                                  0
Creperies_category                                  0
Sicilian_category                                   0
Pakistani_category                                  0
Georgian_category                                   0
Belgian_category                                    0
Noodles_category                                    0
Caribbean_category                                  0
Singaporean_category                                0
Breakfast & Brunch_category                         0
Burgers_category                                    0
South African_category                              0
Venezuelan_category                                 0
Halal_category                                      0
Turkish_category                                    0
Thai_category                                       0
British_category                                    0
Japanese_category                                   0
Shanghainese_category                               0
Middle Eastern_category                             0
Salvadoran_category                                 0
Izakaya_category                                    0
American (New)_category                             0
Malaysian_category                                  0
Moroccan_category                                   0
Taiwanese_category                                  0
Japanese Curry_category                             0
American (Traditional)_category                     0
Cheesesteaks_category                               0
AmbienceRomantic_attribute_False                    0
AmbienceRomantic_attribute_True                     0
AmbienceRomantic_attribute_no_info                  0
AmbienceHipster_attribute_False                     0
AmbienceHipster_attribute_True                      0
AmbienceHipster_attribute_no_info                   0
NoiseLevel_attribute_average                        0
NoiseLevel_attribute_loud                           0
NoiseLevel_attribute_no_info                        0
NoiseLevel_attribute_quiet                          0
NoiseLevel_attribute_very_loud                      0
RestaurantsCounterService_attribute_True            0
RestaurantsCounterService_attribute_no_info         0
DietaryRestrictionsDairy-free_attribute_False       0
DietaryRestrictionsDairy-free_attribute_no_info     0
AmbienceIntimate_attribute_False                    0
AmbienceIntimate_attribute_True                     0
AmbienceIntimate_attribute_no_info                  0
GoodForMealBrunch_attribute_False                   0
GoodForMealBrunch_attribute_True                    0
GoodForMealBrunch_attribute_no_info                 0
BusinessParkingGarage_attribute_False               0
BusinessParkingGarage_attribute_True                0
BusinessParkingGarage_attribute_no_info             0
RestaurantsPriceRange2_attribute_1                  0
RestaurantsPriceRange2_attribute_2                  0
RestaurantsPriceRange2_attribute_3                  0
RestaurantsPriceRange2_attribute_4                  0
RestaurantsPriceRange2_attribute_no_info            0
ByAppointmentOnly_attribute_False                   0
ByAppointmentOnly_attribute_True                    0
ByAppointmentOnly_attribute_no_info                 0
BestNightsSunday_attribute_False                    0
BestNightsSunday_attribute_True                     0
BestNightsSunday_attribute_no_info                  0
AmbienceTrendy_attribute_False                      0
AmbienceTrendy_attribute_True                       0
AmbienceTrendy_attribute_no_info                    0
GoodForKids_attribute_False                         0
GoodForKids_attribute_True                          0
GoodForKids_attribute_no_info                       0
CoatCheck_attribute_False                           0
CoatCheck_attribute_True                            0
CoatCheck_attribute_no_info                         0
RestaurantsTableService_attribute_False             0
RestaurantsTableService_attribute_True              0
RestaurantsTableService_attribute_no_info           0
DietaryRestrictionsVegan_attribute_False            0
DietaryRestrictionsVegan_attribute_no_info          0
BusinessParkingValet_attribute_False                0
BusinessParkingValet_attribute_True                 0
BusinessParkingValet_attribute_no_info              0
Corkage_attribute_False                             0
Corkage_attribute_True                              0
Corkage_attribute_no_info                           0
Music_attribute_no_info                             0
GoodForMealBreakfast_attribute_False                0
GoodForMealBreakfast_attribute_True                 0
GoodForMealBreakfast_attribute_no_info              0
AmbienceDivey_attribute_False                       0
AmbienceDivey_attribute_True                        0
AmbienceDivey_attribute_no_info                     0
DietaryRestrictionsSoy-free_attribute_False         0
DietaryRestrictionsSoy-free_attribute_no_info       0
WheelchairAccessible_attribute_False                0
WheelchairAccessible_attribute_True                 0
WheelchairAccessible_attribute_no_info              0
DietaryRestrictionsHalal_attribute_False            0
DietaryRestrictionsHalal_attribute_no_info          0
RestaurantsTakeOut_attribute_False                  0
RestaurantsTakeOut_attribute_True                   0
RestaurantsTakeOut_attribute_no_info                0
GoodForMealDessert_attribute_False                  0
GoodForMealDessert_attribute_True                   0
GoodForMealDessert_attribute_no_info                0
DietaryRestrictionsGluten-free_attribute_True       0
DietaryRestrictionsGluten-free_attribute_no_info    0
BestNightsWednesday_attribute_False                 0
BestNightsWednesday_attribute_True                  0
BestNightsWednesday_attribute_no_info               0
GoodForMealLatenight_attribute_False                0
GoodForMealLatenight_attribute_True                 0
GoodForMealLatenight_attribute_no_info              0
BestNightsSaturday_attribute_False                  0
BestNightsSaturday_attribute_True                   0
BestNightsSaturday_attribute_no_info                0
MusicLive_attribute_False                           0
MusicLive_attribute_True                            0
MusicLive_attribute_no_info                         0
MusicNo_music_attribute_False                       0
MusicNo_music_attribute_no_info                     0
BusinessParkingLot_attribute_False                  0
BusinessParkingLot_attribute_True                   0
BusinessParkingLot_attribute_no_info                0
AcceptsInsurance_attribute_False                    0
AcceptsInsurance_attribute_no_info                  0
AmbienceCasual_attribute_False                      0
AmbienceCasual_attribute_True                       0
AmbienceCasual_attribute_no_info                    0
HappyHour_attribute_False                           0
HappyHour_attribute_True                            0
HappyHour_attribute_no_info                         0
GoodForMealDinner_attribute_False                   0
GoodForMealDinner_attribute_True                    0
GoodForMealDinner_attribute_no_info                 0
MusicBackground_music_attribute_False               0
MusicBackground_music_attribute_True                0
MusicBackground_music_attribute_no_info             0
MusicKaraoke_attribute_False                        0
MusicKaraoke_attribute_True                         0
MusicKaraoke_attribute_no_info                      0
BusinessParkingValidated_attribute_False            0
BusinessParkingValidated_attribute_True             0
BusinessParkingValidated_attribute_no_info          0
WiFi_attribute_free                                 0
WiFi_attribute_no                                   0
WiFi_attribute_no_info                              0
WiFi_attribute_paid                                 0
DietaryRestrictionsKosher_attribute_False           0
DietaryRestrictionsKosher_attribute_no_info         0
Open24Hours_attribute_False                         0
Open24Hours_attribute_no_info                       0
Ambience_attribute_no_info                          0
GoodForMeal_attribute_no_info                       0
BusinessParking_attribute_no_info                   0
MusicVideo_attribute_False                          0
MusicVideo_attribute_True                           0
MusicVideo_attribute_no_info                        0
Alcohol_attribute_beer_and_wine                     0
Alcohol_attribute_full_bar                          0
Alcohol_attribute_no_info                           0
Alcohol_attribute_none                              0
DietaryRestrictionsVegetarian_attribute_False       0
DietaryRestrictionsVegetarian_attribute_no_info     0
BusinessAcceptsBitcoin_attribute_False              0
BusinessAcceptsBitcoin_attribute_True               0
BusinessAcceptsBitcoin_attribute_no_info            0
BYOB_attribute_False                                0
BYOB_attribute_True                                 0
BYOB_attribute_no_info                              0
AmbienceClassy_attribute_False                      0
AmbienceClassy_attribute_True                       0
AmbienceClassy_attribute_no_info                    0
Smoking_attribute_no                                0
Smoking_attribute_no_info                           0
Smoking_attribute_outdoor                           0
Smoking_attribute_yes                               0
BikeParking_attribute_False                         0
BikeParking_attribute_True                          0
BikeParking_attribute_no_info                       0
MusicDj_attribute_False                             0
MusicDj_attribute_True                              0
MusicDj_attribute_no_info                           0
BestNightsFriday_attribute_False                    0
BestNightsFriday_attribute_True                     0
BestNightsFriday_attribute_no_info                  0
DogsAllowed_attribute_False                         0
DogsAllowed_attribute_True                          0
DogsAllowed_attribute_no_info                       0
AgesAllowed_attribute_21plus                        0
AgesAllowed_attribute_allages                       0
AgesAllowed_attribute_no_info                       0
AmbienceTouristy_attribute_False                    0
AmbienceTouristy_attribute_True                     0
AmbienceTouristy_attribute_no_info                  0
AmbienceUpscale_attribute_False                     0
AmbienceUpscale_attribute_True                      0
AmbienceUpscale_attribute_no_info                   0
OutdoorSeating_attribute_False                      0
OutdoorSeating_attribute_True                       0
OutdoorSeating_attribute_no_info                    0
MusicJukebox_attribute_False                        0
MusicJukebox_attribute_True                         0
MusicJukebox_attribute_no_info                      0
BusinessParkingStreet_attribute_False               0
BusinessParkingStreet_attribute_True                0
BusinessParkingStreet_attribute_no_info             0
RestaurantsAttire_attribute_casual                  0
RestaurantsAttire_attribute_dressy                  0
RestaurantsAttire_attribute_formal                  0
RestaurantsAttire_attribute_no_info                 0
RestaurantsReservations_attribute_False             0
RestaurantsReservations_attribute_True              0
RestaurantsReservations_attribute_no_info           0
GoodForDancing_attribute_False                      0
GoodForDancing_attribute_True                       0
GoodForDancing_attribute_no_info                    0
HasTV_attribute_False                               0
HasTV_attribute_True                                0
HasTV_attribute_no_info                             0
BestNightsTuesday_attribute_False                   0
BestNightsTuesday_attribute_True                    0
BestNightsTuesday_attribute_no_info                 0
BusinessAcceptsCreditCards_attribute_False          0
BusinessAcceptsCreditCards_attribute_True           0
BusinessAcceptsCreditCards_attribute_no_info        0
BestNights_attribute_no_info                        0
RestaurantsGoodForGroups_attribute_False            0
RestaurantsGoodForGroups_attribute_True             0
RestaurantsGoodForGroups_attribute_no_info          0
GoodForMealLunch_attribute_False                    0
GoodForMealLunch_attribute_True                     0
GoodForMealLunch_attribute_no_info                  0
RestaurantsDelivery_attribute_False                 0
RestaurantsDelivery_attribute_True                  0
RestaurantsDelivery_attribute_no_info               0
Caters_attribute_False                              0
Caters_attribute_True                               0
Caters_attribute_no_info                            0
BYOBCorkage_attribute_no                            0
BYOBCorkage_attribute_no_info                       0
BYOBCorkage_attribute_yes_corkage                   0
BYOBCorkage_attribute_yes_free                      0
BestNightsThursday_attribute_False                  0
BestNightsThursday_attribute_True                   0
BestNightsThursday_attribute_no_info                0
DriveThru_attribute_False                           0
DriveThru_attribute_True                            0
DriveThru_attribute_no_info                         0
BestNightsMonday_attribute_False                    0
BestNightsMonday_attribute_True                     0
BestNightsMonday_attribute_no_info                  0
review_id                                           0
user_id                                             0
stars_review                                        0
useful_review                                       0
funny_review                                        0
cool_review                                         0
date                                                0
review_count_user                                   0

In [7]:
merged.info(max_cols=500)

<class 'pandas.DataFrame'>
RangeIndex: 511138 entries, 0 to 511137
Data columns (total 388 columns):
 #    Column                                            Non-Null Count   Dtype
---   ------                                            --------------   -----
 0    business_id                                       511138 non-null  str
 1    stars_business                                    511138 non-null  float64
 2    review_count_review                               511138 non-null  int64
 3    Fuzhou_category                                   511138 non-null  int64
 4    Themed Cafes_category                             511138 non-null  int64
 5    Burmese_category                                  511138 non-null  int64
 6    Falafel_category                                  511138 non-null  int64
 7    Cafes_category                                    511138 non-null  int64
 8    Conveyor Belt Sushi_category                      511138 non-null  int64
 9    Australian_category                               511138 non-null  int64
 10   Sushi Bars_category                               511138 non-null  int64
 11   Mongolian_category                                511138 non-null  int64
 12   New Mexican Cuisine_category                      511138 non-null  int64
 13   Poutineries_category                              511138 non-null  int64
 14   Ethiopian_category                                511138 non-null  int64
 15   Hong Kong Style Cafe_category                     511138 non-null  int64
 16   Cafeteria_category                                511138 non-null  int64
 17   Chicken Shop_category                             511138 non-null  int64
 18   Vegetarian_category                               511138 non-null  int64
 19   Asian Fusion_category                             511138 non-null  int64
 20   Pan Asian_category                                511138 non-null  int64
 21   Dinner Theater_category                           511138 non-null  int64
 22   Hawaiian_category                                 511138 non-null  int64
 23   Fish & Chips_category                             511138 non-null  int64
 24   French_category                                   511138 non-null  int64
 25   Filipino_category                                 511138 non-null  int64
 26   Seafood_category                                  511138 non-null  int64
 27   Szechuan_category                                 511138 non-null  int64
 28   Modern European_category                          511138 non-null  int64
 29   Himalayan/Nepalese_category                       511138 non-null  int64
 30   Senegalese_category                               511138 non-null  int64
 31   Portuguese_category                               511138 non-null  int64
 32   Delis_category                                    511138 non-null  int64
 33   Vegan_category                                    511138 non-null  int64
 34   Spanish_category                                  511138 non-null  int64
 35   Uzbek_category                                    511138 non-null  int64
 36   Iberian_category                                  511138 non-null  int64
 37   Steakhouses_category                              511138 non-null  int64
 38   Italian_category                                  511138 non-null  int64
 39   Trinidadian_category                              511138 non-null  int64
 40   Lebanese_category                                 511138 non-null  int64
 41   Wraps_category                                    511138 non-null  int64
 42   Bangladeshi_category                              511138 non-null  int64
 43   Diners_category                                   511138 non-null  int64
 44   Tapas Bars_category                               511138 non-null  int64
 45   Israeli_category                                  511138 non-null  int64
 46   Pizza_category                                    511138 non-null  int64
 47   Hainan_category                                   511138 non-null  int64
 48   Korean_category                                   511138 non-null  int64
 49   Tapas/Small Plates_category                       511138 non-null  int64
 50   Russian_category                                  511138 non-null  int64
 51   Afghan_category                                   511138 non-null  int64
 52   Mexican_category                                  511138 non-null  int64
 53   Live/Raw Food_category                            511138 non-null  int64
 54   Greek_category                                    511138 non-null  int64
 55   Teppanyaki_category                               511138 non-null  int64
 56   Polish_category                                   511138 non-null  int64
 57   Hot Pot_category                                  511138 non-null  int64
 58   Hot Dogs_category                                 511138 non-null  int64
 59   Hungarian_category                                511138 non-null  int64
 60   Indian_category                                   511138 non-null  int64
 61   Food Stands_category                              511138 non-null  int64
 62   German_category                                   511138 non-null  int64
 63   Southern_category                                 511138 non-null  int64
 64   Indonesian_category                               511138 non-null  int64
 65   African_category                                  511138 non-null  int64
 66   Sardinian_category                                511138 non-null  int64
 67   Buffets_category                                  511138 non-null  int64
 68   Cambodian_category                                511138 non-null  int64
 69   Waffles_category                                  511138 non-null  int64
 70   Sandwiches_category                               511138 non-null  int64
 71   Chinese_category                                  511138 non-null  int64
 72   Dominican_category                                511138 non-null  int64
 73   Barbeque_category                                 511138 non-null  int64
 74   Salad_category                                    511138 non-null  int64
 75   Ukrainian_category                                511138 non-null  int64
 76   Vietnamese_category                               511138 non-null  int64
 77   Soul Food_category                                511138 non-null  int64
 78   Supper Clubs_category                             511138 non-null  int64
 79   Gluten-Free_category                              511138 non-null  int64
 80   Soup_category                                     511138 non-null  int64
 81   Gastropubs_category                               511138 non-null  int64
 82   Tex-Mex_category                                  511138 non-null  int64
 83   Kebab_category                                    511138 non-null  int64
 84   Tacos_category                                    511138 non-null  int64
 85   Scandinavian_category                             511138 non-null  int64
 86   Food Court_category                               511138 non-null  int64
 87   Irish_category                                    511138 non-null  int64
 88   Cajun/Creole_category                             511138 non-null  int64
 89   Armenian_category                                 511138 non-null  int64
 90   Laotian_category                                  511138 non-null  int64
 91   Comfort Food_category                             511138 non-null  int64
 92   Cantonese_category                                511138 non-null  int64
 93   Brasseries_category                               511138 non-null  int64
 94   Kosher_category                                   511138 non-null  int64
 95   Haitian_category                                  511138 non-null  int64
 96   Dim Sum_category                                  511138 non-null  int64
 97   Cuban_category                                    511138 non-null  int64
 98   Chicken Wings_category                            511138 non-null  int64
 99   Colombian_category                                511138 non-null  int64
 100  Peruvian_category                                 511138 non-null  int64
 101  Basque_category                                   511138 non-null  int64
 102  Mediterranean_category                            511138 non-null  int64
 103  Honduran_category                                 511138 non-null  int64
 104  Ramen_category                                    511138 non-null  int64
 105  Pop-Up Restaurants_category                       511138 non-null  int64
 106  Fast Food_category                                511138 non-null  int64
 107  Latin American_category                           511138 non-null  int64
 108  Persian/Iranian_category                          511138 non-null  int64
 109  Puerto Rican_category                             511138 non-null  int64
 110  Brazilian_category                                511138 non-null  int64
 111  Argentine_category                                511138 non-null  int64
 112  Creperies_category                                511138 non-null  int64
 113  Sicilian_category                                 511138 non-null  int64
 114  Pakistani_category                                511138 non-null  int64
 115  Georgian_category                                 511138 non-null  int64
 116  Belgian_category                                  511138 non-null  int64
 117  Noodles_category                                  511138 non-null  int64
 118  Caribbean_category                                511138 non-null  int64
 119  Singaporean_category                              511138 non-null  int64
 120  Breakfast & Brunch_category                       511138 non-null  int64
 121  Burgers_category                                  511138 non-null  int64
 122  South African_category                            511138 non-null  int64
 123  Venezuelan_category                               511138 non-null  int64
 124  Halal_category                                    511138 non-null  int64
 125  Turkish_category                                  511138 non-null  int64
 126  Thai_category                                     511138 non-null  int64
 127  British_category                                  511138 non-null  int64
 128  Japanese_category                                 511138 non-null  int64
 129  Shanghainese_category                             511138 non-null  int64
 130  Middle Eastern_category                           511138 non-null  int64
 131  Salvadoran_category                               511138 non-null  int64
 132  Izakaya_category                                  511138 non-null  int64
 133  American (New)_category                           511138 non-null  int64
 134  Malaysian_category                                511138 non-null  int64
 135  Moroccan_category                                 511138 non-null  int64
 136  Taiwanese_category                                511138 non-null  int64
 137  Japanese Curry_category                           511138 non-null  int64
 138  American (Traditional)_category                   511138 non-null  int64
 139  Cheesesteaks_category                             511138 non-null  int64
 140  AmbienceRomantic_attribute_False                  511138 non-null  int64
 141  AmbienceRomantic_attribute_True                   511138 non-null  int64
 142  AmbienceRomantic_attribute_no_info                511138 non-null  int64
 143  AmbienceHipster_attribute_False                   511138 non-null  int64
 144  AmbienceHipster_attribute_True                    511138 non-null  int64
 145  AmbienceHipster_attribute_no_info                 511138 non-null  int64
 146  NoiseLevel_attribute_average                      511138 non-null  int64
 147  NoiseLevel_attribute_loud                         511138 non-null  int64
 148  NoiseLevel_attribute_no_info                      511138 non-null  int64
 149  NoiseLevel_attribute_quiet                        511138 non-null  int64
 150  NoiseLevel_attribute_very_loud                    511138 non-null  int64
 151  RestaurantsCounterService_attribute_True          511138 non-null  int64
 152  RestaurantsCounterService_attribute_no_info       511138 non-null  int64
 153  DietaryRestrictionsDairy-free_attribute_False     511138 non-null  int64
 154  DietaryRestrictionsDairy-free_attribute_no_info   511138 non-null  int64
 155  AmbienceIntimate_attribute_False                  511138 non-null  int64
 156  AmbienceIntimate_attribute_True                   511138 non-null  int64
 157  AmbienceIntimate_attribute_no_info                511138 non-null  int64
 158  GoodForMealBrunch_attribute_False                 511138 non-null  int64
 159  GoodForMealBrunch_attribute_True                  511138 non-null  int64
 160  GoodForMealBrunch_attribute_no_info               511138 non-null  int64
 161  BusinessParkingGarage_attribute_False             511138 non-null  int64
 162  BusinessParkingGarage_attribute_True              511138 non-null  int64
 163  BusinessParkingGarage_attribute_no_info           511138 non-null  int64
 164  RestaurantsPriceRange2_attribute_1                511138 non-null  int64
 165  RestaurantsPriceRange2_attribute_2                511138 non-null  int64
 166  RestaurantsPriceRange2_attribute_3                511138 non-null  int64
 167  RestaurantsPriceRange2_attribute_4                511138 non-null  int64
 168  RestaurantsPriceRange2_attribute_no_info          511138 non-null  int64
 169  ByAppointmentOnly_attribute_False                 511138 non-null  int64
 170  ByAppointmentOnly_attribute_True                  511138 non-null  int64
 171  ByAppointmentOnly_attribute_no_info               511138 non-null  int64
 172  BestNightsSunday_attribute_False                  511138 non-null  int64
 173  BestNightsSunday_attribute_True                   511138 non-null  int64
 174  BestNightsSunday_attribute_no_info                511138 non-null  int64
 175  AmbienceTrendy_attribute_False                    511138 non-null  int64
 176  AmbienceTrendy_attribute_True                     511138 non-null  int64
 177  AmbienceTrendy_attribute_no_info                  511138 non-null  int64
 178  GoodForKids_attribute_False                       511138 non-null  int64
 179  GoodForKids_attribute_True                        511138 non-null  int64
 180  GoodForKids_attribute_no_info                     511138 non-null  int64
 181  CoatCheck_attribute_False                         511138 non-null  int64
 182  CoatCheck_attribute_True                          511138 non-null  int64
 183  CoatCheck_attribute_no_info                       511138 non-null  int64
 184  RestaurantsTableService_attribute_False           511138 non-null  int64
 185  RestaurantsTableService_attribute_True            511138 non-null  int64
 186  RestaurantsTableService_attribute_no_info         511138 non-null  int64
 187  DietaryRestrictionsVegan_attribute_False          511138 non-null  int64
 188  DietaryRestrictionsVegan_attribute_no_info        511138 non-null  int64
 189  BusinessParkingValet_attribute_False              511138 non-null  int64
 190  BusinessParkingValet_attribute_True               511138 non-null  int64
 191  BusinessParkingValet_attribute_no_info            511138 non-null  int64
 192  Corkage_attribute_False                           511138 non-null  int64
 193  Corkage_attribute_True                            511138 non-null  int64
 194  Corkage_attribute_no_info                         511138 non-null  int64
 195  Music_attribute_no_info                           511138 non-null  int64
 196  GoodForMealBreakfast_attribute_False              511138 non-null  int64
 197  GoodForMealBreakfast_attribute_True               511138 non-null  int64
 198  GoodForMealBreakfast_attribute_no_info            511138 non-null  int64
 199  AmbienceDivey_attribute_False                     511138 non-null  int64
 200  AmbienceDivey_attribute_True                      511138 non-null  int64
 201  AmbienceDivey_attribute_no_info                   511138 non-null  int64
 202  DietaryRestrictionsSoy-free_attribute_False       511138 non-null  int64
 203  DietaryRestrictionsSoy-free_attribute_no_info     511138 non-null  int64
 204  WheelchairAccessible_attribute_False              511138 non-null  int64
 205  WheelchairAccessible_attribute_True               511138 non-null  int64
 206  WheelchairAccessible_attribute_no_info            511138 non-null  int64
 207  DietaryRestrictionsHalal_attribute_False          511138 non-null  int64
 208  DietaryRestrictionsHalal_attribute_no_info        511138 non-null  int64
 209  RestaurantsTakeOut_attribute_False                511138 non-null  int64
 210  RestaurantsTakeOut_attribute_True                 511138 non-null  int64
 211  RestaurantsTakeOut_attribute_no_info              511138 non-null  int64
 212  GoodForMealDessert_attribute_False                511138 non-null  int64
 213  GoodForMealDessert_attribute_True                 511138 non-null  int64
 214  GoodForMealDessert_attribute_no_info              511138 non-null  int64
 215  DietaryRestrictionsGluten-free_attribute_True     511138 non-null  int64
 216  DietaryRestrictionsGluten-free_attribute_no_info  511138 non-null  int64
 217  BestNightsWednesday_attribute_False               511138 non-null  int64
 218  BestNightsWednesday_attribute_True                511138 non-null  int64
 219  BestNightsWednesday_attribute_no_info             511138 non-null  int64
 220  GoodForMealLatenight_attribute_False              511138 non-null  int64
 221  GoodForMealLatenight_attribute_True               511138 non-null  int64
 222  GoodForMealLatenight_attribute_no_info            511138 non-null  int64
 223  BestNightsSaturday_attribute_False                511138 non-null  int64
 224  BestNightsSaturday_attribute_True                 511138 non-null  int64
 225  BestNightsSaturday_attribute_no_info              511138 non-null  int64
 226  MusicLive_attribute_False                         511138 non-null  int64
 227  MusicLive_attribute_True                          511138 non-null  int64
 228  MusicLive_attribute_no_info                       511138 non-null  int64
 229  MusicNo_music_attribute_False                     511138 non-null  int64
 230  MusicNo_music_attribute_no_info                   511138 non-null  int64
 231  BusinessParkingLot_attribute_False                511138 non-null  int64
 232  BusinessParkingLot_attribute_True                 511138 non-null  int64
 233  BusinessParkingLot_attribute_no_info              511138 non-null  int64
 234  AcceptsInsurance_attribute_False                  511138 non-null  int64
 235  AcceptsInsurance_attribute_no_info                511138 non-null  int64
 236  AmbienceCasual_attribute_False                    511138 non-null  int64
 237  AmbienceCasual_attribute_True                     511138 non-null  int64
 238  AmbienceCasual_attribute_no_info                  511138 non-null  int64
 239  HappyHour_attribute_False                         511138 non-null  int64
 240  HappyHour_attribute_True                          511138 non-null  int64
 241  HappyHour_attribute_no_info                       511138 non-null  int64
 242  GoodForMealDinner_attribute_False                 511138 non-null  int64
 243  GoodForMealDinner_attribute_True                  511138 non-null  int64
 244  GoodForMealDinner_attribute_no_info               511138 non-null  int64
 245  MusicBackground_music_attribute_False             511138 non-null  int64
 246  MusicBackground_music_attribute_True              511138 non-null  int64
 247  MusicBackground_music_attribute_no_info           511138 non-null  int64
 248  MusicKaraoke_attribute_False                      511138 non-null  int64

In [8]:
timestamp_format = "%Y-%m-%d %H:%M:%S"
merged["date"] = merged["date"].apply(lambda x: datetime.datetime.strptime(x, timestamp_format))
merged["yelping_since"] = merged["yelping_since"].apply(lambda x: datetime.datetime.strptime(x, timestamp_format))
merged["date"] = (merged["date"] - pd.Timestamp("1970-01-01")) // pd.Timedelta('1s')
merged["yelping_since"] = (merged["yelping_since"] - pd.Timestamp("1970-01-01")) // pd.Timedelta('1s')

In [9]:
merged_no_ids = merged.drop(labels=["review_id", "user_id", "business_id"], axis=1)
display(merged_no_ids)

,stars_business,review_count_review,Fuzhou_category,Themed Cafes_category,Burmese_category,Falafel_category,Cafes_category,Conveyor Belt Sushi_category,Australian_category,Sushi Bars_category,...,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos,number_of_friends
0,4.0,80,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
1,4.0,80,0,0,0,0,0,0,0,0,...,6,1,0,11,28,46,46,26,20,186
2,4.0,80,0,0,0,0,0,0,0,0,...,0,0,0,3,8,2,2,5,0,18
3,4.0,80,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
4,4.0,80,0,0,0,0,0,0,0,0,...,0,1,4,24,51,35,35,13,5,141
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511133,4.5,35,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
511134,4.5,35,0,0,0,0,0,0,0,0,...,0,0,0,3,3,4,4,1,3,6
511135,4.5,35,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
511136,4.5,35,0,0,0,0,0,0,0,0,...,0,0,0,5,0,0,0,0,0,77
511137,4.5,35,0,0,0,0,0,0,0,0,...,0,0,0,6,2,4,4,2,0,79

In [10]:
merged_only_ids = merged[["review_id", "user_id", "business_id"]]
merged_only_ids

                     review_id                 user_id             business_id
0       BXQcBN0iAi1lAUxibGLFzA  6_SpY41LIHZuIaiDs5FMKA  MTSW4McQd7CbVtyjqoe9mw
1       uduvUCvi9w3T2bSGivCfXg  tCXElwhzekJEH6QJe3xs7Q  MTSW4McQd7CbVtyjqoe9mw
2       a0vwPOqDXXZuJkbBW2356g  WqfKtI-aGMmvbA9pPUxNQQ  MTSW4McQd7CbVtyjqoe9mw
3       MKNp_CdR2k2202-c8GN5Dw  3-1va0IQfK-9tUMzfHWfTA  MTSW4McQd7CbVtyjqoe9mw
4       D1GisLDPe84Rrk_R4X2brQ  EouCKoDfzaVG0klEgdDvCQ  MTSW4McQd7CbVtyjqoe9mw
...                        ...                     ...                     ...
511133  qBcwQEQPnLxjkw-xbUIF4Q  6nF5PT1c0dF6EpOgQdF2tw  WnT9NIzQgLlILjPT0kEcsQ
511134  G8fbysnUAUmqq1XWTjMQ4Q  1M78_w4J9f5S8xmUVYyxdQ  WnT9NIzQgLlILjPT0kEcsQ
511135  JKiy0aeyGd3KmXN7uRPFLw  B7TD5yTemGv50y4wM2EVNA  WnT9NIzQgLlILjPT0kEcsQ
511136  JITY01bGbdsiUBznLz9rdg  HI8QwhpeP_ZRY5JZy11VDw  WnT9NIzQgLlILjPT0kEcsQ
511137  VzKF0662H2NLbpbmGv20Ug  CmR9s-2zH20UkmUt5Qwqnw  WnT9NIzQgLlILjPT0kEcsQ

[511138 rows x 3 columns]

In [13]:
user = pd.read_csv(CUSTOM_DATASET_PATH / "user_for_vis.csv")
user

,user_id,name,review_count,yelping_since,useful,funny,cool,elite,fans,average_stars,...,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos,number_of_friends
0,qVc8ODYU5SZjKXVBgXdI7w,Walker,585,2007-01-25 16:47:26,7217,1259,5994,2007,267,3.91,...,55,56,18,232,844,467,467,239,180,14995
1,j14WgRoU_-2ZE1aw1dXrJg,Daniel,4333,2009-01-25 04:35:42,43091,13066,27281,"2009,2010,2011,2012,2013,2014,2015,2016,2017,2...",3138,3.74,...,184,157,251,1847,7054,3131,3131,1521,1946,4646
2,2WnXYQFK0hXEoTxPtV2zvg,Steph,665,2008-07-25 10:41:00,2086,1010,1003,"2009,2010,2011,2012,2013",52,3.32,...,10,17,3,66,96,119,119,35,18,381
3,SZDeASXq7o05mMNLshsdIA,Gwen,224,2005-11-29 04:38:33,512,330,299,"2009,2010,2011",28,4.27,...,1,6,2,12,16,26,26,10,9,131
4,hA5lMy-EnncsH4JoR-hFGQ,Karen,79,2007-01-05 19:40:59,29,15,7,NaN,1,3.54,...,0,0,0,1,1,0,0,0,0,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1987892,fB3jbHi3m0L2KgGOxBv6uw,Jerrold,23,2015-01-06 00:31:31,7,0,0,NaN,0,4.92,...,0,0,0,0,0,0,0,0,0,1
1987893,68czcr4BxJyMQ9cJBm6C7Q,Jane,1,2016-06-14 07:20:52,0,0,0,NaN,0,5.00,...,0,0,0,0,0,0,0,0,0,1
1987894,1x3KMskYxOuJCjRz70xOqQ,Shomari,4,2017-02-04 15:31:58,1,1,0,NaN,0,2.00,...,0,0,0,0,0,0,0,0,0,1
1987895,ulfGl4tdbrH05xKzh5lnog,Susanne,2,2011-01-14 00:29:08,0,0,0,NaN,0,3.00,...,0,0,0,0,0,0,0,0,0,1
1987896,wL5jPrLRVCK_Pmo4lM1zpA,Isa,2,2020-12-19 02:32:39,0,0,0,NaN,0,5.00,...,0,0,0,0,0,0,0,0,0,1

In [ ]:
# merged_no_ids_copy = merged_no_ids.copy()
# merged_no_ids_copy = merged_no_ids_copy.drop(columns=["review_count_user", "yelping_since", "useful_user", "funny_user", "cool_user", "fans", "average_stars", "compliment_hot", "compliment_more", "compliment_profile", "compliment_cute", "compliment_list", "compliment_note", "compliment_plain", "compliment_cool", "compliment_funny", "compliment_writer", "compliment_photos", "number_of_friends", "useful_review", "funny_review", "cool_review", "stars_review"])
# merged_no_ids_copy

,stars_business,review_count_review,Fuzhou_category,Themed Cafes_category,Burmese_category,Falafel_category,Cafes_category,Conveyor Belt Sushi_category,Australian_category,Sushi Bars_category,...,BestNightsThursday_attribute_False,BestNightsThursday_attribute_True,BestNightsThursday_attribute_no_info,DriveThru_attribute_False,DriveThru_attribute_True,DriveThru_attribute_no_info,BestNightsMonday_attribute_False,BestNightsMonday_attribute_True,BestNightsMonday_attribute_no_info,date
0,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.547730
1,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.510133
2,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.513276
3,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.783217
4,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.513282
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511133,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.933705
511134,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.932890
511135,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.951791
511136,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.943997
511137,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.877333

In [11]:
scaler = MinMaxScaler(feature_range=(0, 1))
scaler.fit(merged_no_ids)
merged_no_ids = pd.DataFrame(scaler.transform(merged_no_ids), columns=merged_no_ids.columns)
display(merged_no_ids)

,stars_business,review_count_review,Fuzhou_category,Themed Cafes_category,Burmese_category,Falafel_category,Cafes_category,Conveyor Belt Sushi_category,Australian_category,Sushi Bars_category,...,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos,number_of_friends
0,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000063,0.000000,0.000000
1,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000852,0.000336,0.000000,0.000186,0.000277,0.000921,0.000921,0.001632,0.000356,0.012338
2,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000051,0.000079,0.000040,0.000040,0.000314,0.000000,0.001134
3,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000200
4,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000336,0.001534,0.000407,0.000504,0.000700,0.000700,0.000816,0.000089,0.009337
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511133,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000010,0.000000,0.000000,0.000000,0.000000,0.000000
511134,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000051,0.000030,0.000080,0.000080,0.000063,0.000053,0.000333
511135,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
511136,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000085,0.000000,0.000000,0.000000,0.000000,0.000000,0.005069
511137,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000102,0.000020,0.000080,0.000080,0.000126,0.000000,0.005202

In [12]:
merged_no_ids_copy = merged_no_ids.copy()
merged_no_ids_copy = merged_no_ids_copy.drop(columns=["review_count_user", "yelping_since", "useful_user", "funny_user", "cool_user", "fans", "average_stars", "compliment_hot", "compliment_more", "compliment_profile", "compliment_cute", "compliment_list", "compliment_note", "compliment_plain", "compliment_cool", "compliment_funny", "compliment_writer", "compliment_photos", "number_of_friends", "useful_review", "funny_review", "cool_review", "stars_review"])
merged_no_ids_copy

,stars_business,review_count_review,Fuzhou_category,Themed Cafes_category,Burmese_category,Falafel_category,Cafes_category,Conveyor Belt Sushi_category,Australian_category,Sushi Bars_category,...,BestNightsThursday_attribute_False,BestNightsThursday_attribute_True,BestNightsThursday_attribute_no_info,DriveThru_attribute_False,DriveThru_attribute_True,DriveThru_attribute_no_info,BestNightsMonday_attribute_False,BestNightsMonday_attribute_True,BestNightsMonday_attribute_no_info,date
0,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.547730
1,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.510133
2,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.513276
3,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.783217
4,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.513282
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511133,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.933705
511134,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.932890
511135,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.951791
511136,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.943997
511137,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.877333

In [13]:
merged = merged_only_ids.join(merged_no_ids)
display(merged)

,review_id,user_id,business_id,stars_business,review_count_review,Fuzhou_category,Themed Cafes_category,Burmese_category,Falafel_category,Cafes_category,...,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos,number_of_friends
0,BXQcBN0iAi1lAUxibGLFzA,6_SpY41LIHZuIaiDs5FMKA,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000063,0.000000,0.000000
1,uduvUCvi9w3T2bSGivCfXg,tCXElwhzekJEH6QJe3xs7Q,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.000852,0.000336,0.000000,0.000186,0.000277,0.000921,0.000921,0.001632,0.000356,0.012338
2,a0vwPOqDXXZuJkbBW2356g,WqfKtI-aGMmvbA9pPUxNQQ,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000051,0.000079,0.000040,0.000040,0.000314,0.000000,0.001134
3,MKNp_CdR2k2202-c8GN5Dw,3-1va0IQfK-9tUMzfHWfTA,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000200
4,D1GisLDPe84Rrk_R4X2brQ,EouCKoDfzaVG0klEgdDvCQ,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000336,0.001534,0.000407,0.000504,0.000700,0.000700,0.000816,0.000089,0.009337
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511133,qBcwQEQPnLxjkw-xbUIF4Q,6nF5PT1c0dF6EpOgQdF2tw,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000010,0.000000,0.000000,0.000000,0.000000,0.000000
511134,G8fbysnUAUmqq1XWTjMQ4Q,1M78_w4J9f5S8xmUVYyxdQ,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000051,0.000030,0.000080,0.000080,0.000063,0.000053,0.000333
511135,JKiy0aeyGd3KmXN7uRPFLw,B7TD5yTemGv50y4wM2EVNA,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
511136,JITY01bGbdsiUBznLz9rdg,HI8QwhpeP_ZRY5JZy11VDw,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000085,0.000000,0.000000,0.000000,0.000000,0.000000,0.005069
511137,VzKF0662H2NLbpbmGv20Ug,CmR9s-2zH20UkmUt5Qwqnw,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000102,0.000020,0.000080,0.000080,0.000126,0.000000,0.005202

In [14]:
merged_copy = merged_only_ids.join(merged_no_ids_copy)
display(merged_copy)

,review_id,user_id,business_id,stars_business,review_count_review,Fuzhou_category,Themed Cafes_category,Burmese_category,Falafel_category,Cafes_category,...,BestNightsThursday_attribute_False,BestNightsThursday_attribute_True,BestNightsThursday_attribute_no_info,DriveThru_attribute_False,DriveThru_attribute_True,DriveThru_attribute_no_info,BestNightsMonday_attribute_False,BestNightsMonday_attribute_True,BestNightsMonday_attribute_no_info,date
0,BXQcBN0iAi1lAUxibGLFzA,6_SpY41LIHZuIaiDs5FMKA,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.547730
1,uduvUCvi9w3T2bSGivCfXg,tCXElwhzekJEH6QJe3xs7Q,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.510133
2,a0vwPOqDXXZuJkbBW2356g,WqfKtI-aGMmvbA9pPUxNQQ,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.513276
3,MKNp_CdR2k2202-c8GN5Dw,3-1va0IQfK-9tUMzfHWfTA,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.783217
4,D1GisLDPe84Rrk_R4X2brQ,EouCKoDfzaVG0klEgdDvCQ,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.513282
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511133,qBcwQEQPnLxjkw-xbUIF4Q,6nF5PT1c0dF6EpOgQdF2tw,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.933705
511134,G8fbysnUAUmqq1XWTjMQ4Q,1M78_w4J9f5S8xmUVYyxdQ,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.932890
511135,JKiy0aeyGd3KmXN7uRPFLw,B7TD5yTemGv50y4wM2EVNA,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.951791
511136,JITY01bGbdsiUBznLz9rdg,HI8QwhpeP_ZRY5JZy11VDw,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.943997
511137,VzKF0662H2NLbpbmGv20Ug,CmR9s-2zH20UkmUt5Qwqnw,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.877333

In [15]:
merged.value_counts("user_id")

user_id
ET8n-r7glWYqZhuR6GcdNw    610
vFd8aBLg1kFcd0kCkoi-xw    447
_BcWyKQL16ndpBdggh2kNA    441
bJ5FtCtZX3ZZacz2_2PJjA    375
0DB3Irpf_ETVXu_Ou9vPow    357
                         ...
ogGTGzUzKn1x5-ddTU4yfQ      1
YqiMF5KzIw8xP494HNuKdw      1
4rNNfQm1tB1xOVQ9ZduzNA      1
7Ka3Smzb7hlHi8gk0wByjw      1
B7TD5yTemGv50y4wM2EVNA      1
Name: count, Length: 178325, dtype: int64

In [16]:
indexes = merged.value_counts("user_id")[(merged.value_counts("user_id") == 5)].index
indexes

Index(['nDFRVVcNLLUt-F_s0yBIPA', 'STq_SEa2rTEGPgKSP388Sw',
       'H_CJLohiZzbnHWBI-P-u8Q', 'dbqRq6_KOKjcl2uT51DLKA',
       'Qth4n3N3XYzEgIIfXDVXww', '8mNhnIUBUTsi4BwkIyKUqw',
       'aRYk2snBNhxAk6hBgWD-Aw', 'QKlRvN4cJszeKI06usG6dA',
       '_rVlbC15nRQPSq-o3hMzdQ', 'EXFvkdyj-mhzm3PA2ESHLg',
       ...
       'GQgH--hxKJisGmfsKj0xDA', 'Zy8NOrdYcTaKJxbfdM0kHQ',
       'nh6ArLduHi_53eMPMW0fgw', 'OxaqY6xoDhFFxyICEX4QQQ',
       'EWLuooWEKiGZlxl3jccVyA', 'LU0KeX-SHEFhI77xqDueoA',
       'MKkCT6R15R2nrURE6VTOgA', 'kJModxtvXak455L9xo9xXw',
       'RhoZYeIa3tP0nTEitoNFzA', 'knE5x-gQ6ALjcXHpSkpkVw'],
      dtype='str', name='user_id', length=4269)

In [17]:
merged

,review_id,user_id,business_id,stars_business,review_count_review,Fuzhou_category,Themed Cafes_category,Burmese_category,Falafel_category,Cafes_category,...,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos,number_of_friends
0,BXQcBN0iAi1lAUxibGLFzA,6_SpY41LIHZuIaiDs5FMKA,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000063,0.000000,0.000000
1,uduvUCvi9w3T2bSGivCfXg,tCXElwhzekJEH6QJe3xs7Q,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.000852,0.000336,0.000000,0.000186,0.000277,0.000921,0.000921,0.001632,0.000356,0.012338
2,a0vwPOqDXXZuJkbBW2356g,WqfKtI-aGMmvbA9pPUxNQQ,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000051,0.000079,0.000040,0.000040,0.000314,0.000000,0.001134
3,MKNp_CdR2k2202-c8GN5Dw,3-1va0IQfK-9tUMzfHWfTA,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000200
4,D1GisLDPe84Rrk_R4X2brQ,EouCKoDfzaVG0klEgdDvCQ,MTSW4McQd7CbVtyjqoe9mw,0.750,0.013121,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000336,0.001534,0.000407,0.000504,0.000700,0.000700,0.000816,0.000089,0.009337
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511133,qBcwQEQPnLxjkw-xbUIF4Q,6nF5PT1c0dF6EpOgQdF2tw,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000010,0.000000,0.000000,0.000000,0.000000,0.000000
511134,G8fbysnUAUmqq1XWTjMQ4Q,1M78_w4J9f5S8xmUVYyxdQ,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000051,0.000030,0.000080,0.000080,0.000063,0.000053,0.000333
511135,JKiy0aeyGd3KmXN7uRPFLw,B7TD5yTemGv50y4wM2EVNA,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
511136,JITY01bGbdsiUBznLz9rdg,HI8QwhpeP_ZRY5JZy11VDw,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000085,0.000000,0.000000,0.000000,0.000000,0.000000,0.005069
511137,VzKF0662H2NLbpbmGv20Ug,CmR9s-2zH20UkmUt5Qwqnw,WnT9NIzQgLlILjPT0kEcsQ,0.875,0.005248,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000102,0.000020,0.000080,0.000080,0.000126,0.000000,0.005202

In [18]:
user_matrix = np.array(
    [merged[merged["user_id"] == user_id].sort_values("date").drop(labels=["review_id", "user_id", "business_id"], axis=1).to_numpy() for user_id in indexes]
)

In [19]:
user_matrix_y = np.array(
    [merged_copy[merged_copy["user_id"] == user_id].sort_values("date").drop(labels=["review_id", "user_id", "business_id", "date"], axis=1).to_numpy() for user_id in indexes]
)

In [20]:
user_matrix.shape

(4269, 5, 385)

In [21]:
user_matrix_y.shape

(4269, 5, 361)

In [22]:
user_matrix.dtype

dtype('float64')

In [23]:
user_matrix_y.dtype

dtype('float64')

In [24]:
# user_matrix = user_matrix[~np.isnan(user_matrix)]
user_matrix

array([[[6.25000000e-01, 6.52554234e-02, 0.00000000e+00, ...,
         1.25517761e-04, 0.00000000e+00, 2.66773376e-04],
        [8.75000000e-01, 1.24212736e-02, 0.00000000e+00, ...,
         1.25517761e-04, 0.00000000e+00, 2.66773376e-04],
        [8.75000000e-01, 1.22463261e-03, 0.00000000e+00, ...,
         1.25517761e-04, 0.00000000e+00, 2.66773376e-04],
        [7.50000000e-01, 1.31210637e-02, 0.00000000e+00, ...,
         1.25517761e-04, 0.00000000e+00, 2.66773376e-04],
        [5.00000000e-01, 3.67389783e-02, 0.00000000e+00, ...,
         1.25517761e-04, 0.00000000e+00, 2.66773376e-04]],

       [[7.50000000e-01, 1.12841148e-01, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [5.00000000e-01, 5.37088873e-02, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [7.50000000e-01, 4.19874038e-02, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [7.50000000e-01, 6.77046886e-02, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [5.00000000e-01, 3.46396081e-02, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00]],

       [[8.75000000e-01, 1.07417775e-01, 0.00000000e+00, ...,
         6.27588804e-05, 1.78240411e-05, 1.73402694e-03],
        [7.50000000e-01, 3.56892932e-02, 0.00000000e+00, ...,
         6.27588804e-05, 1.78240411e-05, 1.73402694e-03],
        [7.50000000e-01, 5.10846746e-02, 0.00000000e+00, ...,
         6.27588804e-05, 1.78240411e-05, 1.73402694e-03],
        [8.75000000e-01, 1.73547936e-01, 0.00000000e+00, ...,
         6.27588804e-05, 1.78240411e-05, 1.73402694e-03],
        [7.50000000e-01, 4.19874038e-02, 0.00000000e+00, ...,
         6.27588804e-05, 1.78240411e-05, 1.73402694e-03]],

       ...,

       [[7.50000000e-01, 4.65360392e-02, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 1.40056022e-03],
        [6.25000000e-01, 3.18404479e-02, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 1.40056022e-03],
        [6.25000000e-01, 4.49615115e-02, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 1.40056022e-03],
        [8.75000000e-01, 5.82575227e-02, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 1.40056022e-03],
        [8.75000000e-01, 5.82575227e-02, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 1.40056022e-03]],

       [[8.75000000e-01, 1.24212736e-02, 0.00000000e+00, ...,
         0.00000000e+00, 5.34721232e-05, 7.13618781e-03],
        [8.75000000e-01, 1.24212736e-02, 0.00000000e+00, ...,
         0.00000000e+00, 5.34721232e-05, 7.13618781e-03],
        [6.25000000e-01, 3.18404479e-02, 0.00000000e+00, ...,
         0.00000000e+00, 5.34721232e-05, 7.13618781e-03],
        [8.75000000e-01, 1.24212736e-02, 0.00000000e+00, ...,
         0.00000000e+00, 5.34721232e-05, 7.13618781e-03],
        [8.75000000e-01, 1.24212736e-02, 0.00000000e+00, ...,
         0.00000000e+00, 5.34721232e-05, 7.13618781e-03]],

       [[8.75000000e-01, 1.27711686e-02, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 2.00080032e-04],
        [8.75000000e-01, 1.27711686e-02, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 2.00080032e-04],
        [8.75000000e-01, 1.27711686e-02, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 2.00080032e-04],
        [8.75000000e-01, 1.27711686e-02, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 2.00080032e-04],
        [8.75000000e-01, 1.27711686e-02, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 2.00080032e-04]]],
      shape=(4269, 5, 385))

In [25]:
x = user_matrix[:, :4, :]
y = user_matrix_y[:, 4:, :]

In [26]:
display(x.shape)
display(y.shape)

(4269, 4, 385)

(4269, 1, 361)

In [23]:
display(0.1/(32*4*385))
display(1/(32*4*385))
display((0.1/(32*4*385)) + (1/(32*4*385)))

2.0292207792207792e-06

2.0292207792207792e-05

2.232142857142857e-05

In [27]:
model = Sequential([
    LSTM(512, activation="tanh", return_sequences=True, input_shape=(4, 385)),  # First LSTM layer
    LSTM(384, activation="tanh"),  # Second LSTM layer
    Dense(256, activation="relu"),
    # Dropout(0.1),
    Dense(361, activation="tanh"),
])
optimizer = keras.optimizers.Adam()
optimizer.learning_rate.assign(0.000001)
model.compile(optimizer=optimizer, loss='mse', metrics=['mae'])
model.summary()

E0000 00:00:1776268746.931979   16412 cuda_platform.cc:52] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)
/home/kristofs/School/ISA/ISA_project/.venv/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 4, 512)         │     1,839,104 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 384)            │     1,377,792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 256)            │        98,560 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 361)            │        92,777 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,408,233 (13.00 MB)

 Trainable params: 3,408,233 (13.00 MB)

 Non-trainable params: 0 (0.00 B)

In [28]:
history = model.fit(x, y, epochs=300, batch_size=256, verbose=1)

Epoch 1/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 7s 148ms/step - loss: 0.2115 - mae: 0.2335
Epoch 2/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 128ms/step - loss: 0.2110 - mae: 0.2331
Epoch 3/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.2105 - mae: 0.2328
Epoch 4/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 116ms/step - loss: 0.2100 - mae: 0.2325
Epoch 5/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.2095 - mae: 0.2323
Epoch 6/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 116ms/step - loss: 0.2090 - mae: 0.2321
Epoch 7/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.2085 - mae: 0.2320
Epoch 8/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.2080 - mae: 0.2320
Epoch 9/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 116ms/step - loss: 0.2075 - mae: 0.2319
Epoch 10/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.2070 - mae: 0.2320
Epoch 11/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.2065 - mae: 0.2320
Epoch 12/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.2060 - mae: 0.2322
Epoch 13/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.2055 - mae: 0.2323
Epoch 14/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.2049 - mae: 0.2325
Epoch 15/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.2044 - mae: 0.2328
Epoch 16/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.2039 - mae: 0.2330
Epoch 17/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.2034 - mae: 0.2333
Epoch 18/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.2029 - mae: 0.2337
Epoch 19/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.2023 - mae: 0.2340
Epoch 20/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.2018 - mae: 0.2344
Epoch 21/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.2012 - mae: 0.2348
Epoch 22/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.2007 - mae: 0.2352
Epoch 23/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.2001 - mae: 0.2356
Epoch 24/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1995 - mae: 0.2361
Epoch 25/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1989 - mae: 0.2366
Epoch 26/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1984 - mae: 0.2371
Epoch 27/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1978 - mae: 0.2376
Epoch 28/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1972 - mae: 0.2381
Epoch 29/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1966 - mae: 0.2386
Epoch 30/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1960 - mae: 0.2391
Epoch 31/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1954 - mae: 0.2396
Epoch 32/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1948 - mae: 0.2402
Epoch 33/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1942 - mae: 0.2407
Epoch 34/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1935 - mae: 0.2413
Epoch 35/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1929 - mae: 0.2418
Epoch 36/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1923 - mae: 0.2424
Epoch 37/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 120ms/step - loss: 0.1916 - mae: 0.2429
Epoch 38/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1909 - mae: 0.2435
Epoch 39/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1902 - mae: 0.2441
Epoch 40/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1895 - mae: 0.2446
Epoch 41/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1889 - mae: 0.2452
Epoch 42/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1881 - mae: 0.2458
Epoch 43/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1874 - mae: 0.2464
Epoch 44/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1867 - mae: 0.2469
Epoch 45/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1860 - mae: 0.2475
Epoch 46/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1852 - mae: 0.2481
Epoch 47/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1844 - mae: 0.2486
Epoch 48/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1837 - mae: 0.2492
Epoch 49/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1829 - mae: 0.2497
Epoch 50/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1821 - mae: 0.2503
Epoch 51/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1814 - mae: 0.2508
Epoch 52/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1806 - mae: 0.2513
Epoch 53/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1798 - mae: 0.2518
Epoch 54/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1790 - mae: 0.2523
Epoch 55/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1782 - mae: 0.2528
Epoch 56/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1774 - mae: 0.2533
Epoch 57/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1766 - mae: 0.2538
Epoch 58/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1759 - mae: 0.2542
Epoch 59/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1750 - mae: 0.2547
Epoch 60/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1742 - mae: 0.2551
Epoch 61/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1734 - mae: 0.2555
Epoch 62/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1726 - mae: 0.2559
Epoch 63/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1718 - mae: 0.2563
Epoch 64/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1710 - mae: 0.2567
Epoch 65/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1702 - mae: 0.2571
Epoch 66/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1694 - mae: 0.2574
Epoch 67/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1686 - mae: 0.2577
Epoch 68/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1677 - mae: 0.2580
Epoch 69/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1669 - mae: 0.2583
Epoch 70/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1661 - mae: 0.2586
Epoch 71/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1653 - mae: 0.2588
Epoch 72/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1645 - mae: 0.2590
Epoch 73/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1636 - mae: 0.2592
Epoch 74/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1628 - mae: 0.2594
Epoch 75/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1620 - mae: 0.2596
Epoch 76/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1612 - mae: 0.2597
Epoch 77/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1604 - mae: 0.2598
Epoch 78/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1597 - mae: 0.2599
Epoch 79/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 120ms/step - loss: 0.1589 - mae: 0.2600
Epoch 80/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1581 - mae: 0.2601
Epoch 81/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1573 - mae: 0.2601
Epoch 82/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1566 - mae: 0.2601
Epoch 83/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1558 - mae: 0.2601
Epoch 84/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1550 - mae: 0.2601
Epoch 85/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1543 - mae: 0.2600
Epoch 86/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1536 - mae: 0.2599
Epoch 87/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 116ms/step - loss: 0.1528 - mae: 0.2598
Epoch 88/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1521 - mae: 0.2597
Epoch 89/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1514 - mae: 0.2596
Epoch 90/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1507 - mae: 0.2595
Epoch 91/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1500 - mae: 0.2593
Epoch 92/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1492 - mae: 0.2591
Epoch 93/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1485 - mae: 0.2590
Epoch 94/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.1478 - mae: 0.2588
Epoch 95/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1471 - mae: 0.2586
Epoch 96/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1464 - mae: 0.2584
Epoch 97/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1457 - mae: 0.2581
Epoch 98/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 113ms/step - loss: 0.1450 - mae: 0.2579
Epoch 99/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 134ms/step - loss: 0.1444 - mae: 0.2576
Epoch 100/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 134ms/step - loss: 0.1437 - mae: 0.2573
Epoch 101/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 114ms/step - loss: 0.1431 - mae: 0.2570
Epoch 102/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 116ms/step - loss: 0.1424 - mae: 0.2567
Epoch 103/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1418 - mae: 0.2563
Epoch 104/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1411 - mae: 0.2560
Epoch 105/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1405 - mae: 0.2556
Epoch 106/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1399 - mae: 0.2552
Epoch 107/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1393 - mae: 0.2549
Epoch 108/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1386 - mae: 0.2545
Epoch 109/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1380 - mae: 0.2541
Epoch 110/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1374 - mae: 0.2537
Epoch 111/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1368 - mae: 0.2532
Epoch 112/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 125ms/step - loss: 0.1363 - mae: 0.2528
Epoch 113/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 131ms/step - loss: 0.1357 - mae: 0.2524
Epoch 114/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 123ms/step - loss: 0.1351 - mae: 0.2519
Epoch 115/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 129ms/step - loss: 0.1345 - mae: 0.2515
Epoch 116/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 125ms/step - loss: 0.1339 - mae: 0.2510
Epoch 117/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 125ms/step - loss: 0.1334 - mae: 0.2505
Epoch 118/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 123ms/step - loss: 0.1328 - mae: 0.2500
Epoch 119/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 124ms/step - loss: 0.1323 - mae: 0.2496
Epoch 120/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 124ms/step - loss: 0.1317 - mae: 0.2491
Epoch 121/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 122ms/step - loss: 0.1312 - mae: 0.2486
Epoch 122/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1306 - mae: 0.2481
Epoch 123/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 111ms/step - loss: 0.1301 - mae: 0.2476
Epoch 124/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1296 - mae: 0.2471
Epoch 125/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 120ms/step - loss: 0.1290 - mae: 0.2466
Epoch 126/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1285 - mae: 0.2461
Epoch 127/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1280 - mae: 0.2456
Epoch 128/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1275 - mae: 0.2451
Epoch 129/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 121ms/step - loss: 0.1269 - mae: 0.2446
Epoch 130/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 120ms/step - loss: 0.1264 - mae: 0.2441
Epoch 131/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 120ms/step - loss: 0.1259 - mae: 0.2436
Epoch 132/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1254 - mae: 0.2432
Epoch 133/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 120ms/step - loss: 0.1249 - mae: 0.2427
Epoch 134/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1244 - mae: 0.2422
Epoch 135/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1240 - mae: 0.2417
Epoch 136/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1235 - mae: 0.2412
Epoch 137/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 122ms/step - loss: 0.1230 - mae: 0.2408
Epoch 138/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1225 - mae: 0.2403
Epoch 139/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1220 - mae: 0.2398
Epoch 140/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1215 - mae: 0.2393
Epoch 141/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 120ms/step - loss: 0.1210 - mae: 0.2388
Epoch 142/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1205 - mae: 0.2383
Epoch 143/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1200 - mae: 0.2378
Epoch 144/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1196 - mae: 0.2373
Epoch 145/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1191 - mae: 0.2368
Epoch 146/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 121ms/step - loss: 0.1186 - mae: 0.2363
Epoch 147/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 120ms/step - loss: 0.1181 - mae: 0.2358
Epoch 148/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1177 - mae: 0.2353
Epoch 149/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1172 - mae: 0.2348
Epoch 150/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 120ms/step - loss: 0.1168 - mae: 0.2343
Epoch 151/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1163 - mae: 0.2338
Epoch 152/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1159 - mae: 0.2333
Epoch 153/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1154 - mae: 0.2328
Epoch 154/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1150 - mae: 0.2323
Epoch 155/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1145 - mae: 0.2318
Epoch 156/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1141 - mae: 0.2313
Epoch 157/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1137 - mae: 0.2307
Epoch 158/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1132 - mae: 0.2302
Epoch 159/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1128 - mae: 0.2297
Epoch 160/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1124 - mae: 0.2292
Epoch 161/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 120ms/step - loss: 0.1120 - mae: 0.2287
Epoch 162/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 120ms/step - loss: 0.1116 - mae: 0.2282
Epoch 163/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 120ms/step - loss: 0.1112 - mae: 0.2278
Epoch 164/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 120ms/step - loss: 0.1108 - mae: 0.2273
Epoch 165/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 120ms/step - loss: 0.1103 - mae: 0.2268
Epoch 166/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1100 - mae: 0.2263
Epoch 167/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1096 - mae: 0.2258
Epoch 168/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1092 - mae: 0.2253
Epoch 169/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 121ms/step - loss: 0.1088 - mae: 0.2248
Epoch 170/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1084 - mae: 0.2242
Epoch 171/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1080 - mae: 0.2237
Epoch 172/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 121ms/step - loss: 0.1076 - mae: 0.2232
Epoch 173/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1072 - mae: 0.2227
Epoch 174/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1069 - mae: 0.2222
Epoch 175/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1065 - mae: 0.2217
Epoch 176/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 121ms/step - loss: 0.1061 - mae: 0.2212
Epoch 177/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1058 - mae: 0.2207
Epoch 178/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1054 - mae: 0.2201
Epoch 179/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1051 - mae: 0.2196
Epoch 180/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1047 - mae: 0.2191
Epoch 181/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1043 - mae: 0.2185
Epoch 182/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1040 - mae: 0.2180
Epoch 183/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 120ms/step - loss: 0.1037 - mae: 0.2175
Epoch 184/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1033 - mae: 0.2170
Epoch 185/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1030 - mae: 0.2164
Epoch 186/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1026 - mae: 0.2159
Epoch 187/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 121ms/step - loss: 0.1023 - mae: 0.2154
Epoch 188/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1020 - mae: 0.2148
Epoch 189/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1017 - mae: 0.2143
Epoch 190/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 120ms/step - loss: 0.1013 - mae: 0.2138
Epoch 191/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 120ms/step - loss: 0.1010 - mae: 0.2133
Epoch 192/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1007 - mae: 0.2127
Epoch 193/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.1004 - mae: 0.2122
Epoch 194/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.1001 - mae: 0.2117
Epoch 195/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.0998 - mae: 0.2111
Epoch 196/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.0995 - mae: 0.2106
Epoch 197/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 120ms/step - loss: 0.0992 - mae: 0.2101
Epoch 198/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.0989 - mae: 0.2096
Epoch 199/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.0986 - mae: 0.2090
Epoch 200/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 121ms/step - loss: 0.0983 - mae: 0.2085
Epoch 201/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.0980 - mae: 0.2080
Epoch 202/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.0977 - mae: 0.2074
Epoch 203/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.0974 - mae: 0.2069
Epoch 204/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.0970 - mae: 0.2064
Epoch 205/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.0968 - mae: 0.2059
Epoch 206/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.0965 - mae: 0.2054
Epoch 207/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 120ms/step - loss: 0.0962 - mae: 0.2049
Epoch 208/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.0959 - mae: 0.2044
Epoch 209/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.0956 - mae: 0.2039
Epoch 210/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 120ms/step - loss: 0.0953 - mae: 0.2034
Epoch 211/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.0951 - mae: 0.2029
Epoch 212/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.0948 - mae: 0.2024
Epoch 213/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 121ms/step - loss: 0.0945 - mae: 0.2020
Epoch 214/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.0942 - mae: 0.2015
Epoch 215/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.0940 - mae: 0.2010
Epoch 216/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.0937 - mae: 0.2005
Epoch 217/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.0935 - mae: 0.2000
Epoch 218/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.0932 - mae: 0.1995
Epoch 219/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.0930 - mae: 0.1990
Epoch 220/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 120ms/step - loss: 0.0927 - mae: 0.1985
Epoch 221/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.0925 - mae: 0.1981
Epoch 222/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 117ms/step - loss: 0.0922 - mae: 0.1976
Epoch 223/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 120ms/step - loss: 0.0920 - mae: 0.1971
Epoch 224/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.0917 - mae: 0.1966
Epoch 225/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.0915 - mae: 0.1961
Epoch 226/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 120ms/step - loss: 0.0913 - mae: 0.1957
Epoch 227/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.0910 - mae: 0.1952
Epoch 228/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.0908 - mae: 0.1947
Epoch 229/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.0906 - mae: 0.1942
Epoch 230/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 118ms/step - loss: 0.0903 - mae: 0.1938
Epoch 231/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.0901 - mae: 0.1933
Epoch 232/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 120ms/step - loss: 0.0899 - mae: 0.1929
Epoch 233/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.0897 - mae: 0.1924
Epoch 234/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.0895 - mae: 0.1920
Epoch 235/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 120ms/step - loss: 0.0893 - mae: 0.1915
Epoch 236/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 120ms/step - loss: 0.0890 - mae: 0.1911
Epoch 237/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.0888 - mae: 0.1907
Epoch 238/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 120ms/step - loss: 0.0886 - mae: 0.1903
Epoch 239/300
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - loss: 0.0884 - mae: 0.1899
Epoch 240/300